'use client'

import { useState } from 'react'
import Icon from '@/components/ui/Icon'
import type { EhcpPlanWithOutcomes, EhcpSections, EhcpAuditEntryRow } from '@/app/actions/ehcp'
import { approveGeneratedEhcp, updateEhcpSection, getEhcpAuditLog } from '@/app/actions/ehcp'
import EhcpOutcomeTracker from '@/components/homework/EhcpOutcomeTracker'

const SECTION_KEYS = ['A','B','C','D','E','F','G','H1','H2','I','J','K'] as const
const SECTION_LABELS: Record<string, string> = {
  A:  'Section A — Views and aspirations of child and parents',
  B:  'Section B — Special educational needs',
  C:  'Section C — Health needs',
  D:  'Section D — Social care needs',
  E:  'Section E — Educational outcomes',
  F:  'Section F — Special educational provision',
  G:  'Section G — Health provision',
  H1: 'Section H1 — Social care provision (local authority)',
  H2: 'Section H2 — Other social care provision',
  I:  'Section I — School placement',
  J:  'Section J — Personal budget',
  K:  'Section K — Appendices',
}

const ROLE_LABELS: Record<string, string> = {
  SENCO: 'SENCO', TEACHER: 'Teacher', HEAD_OF_DEPT: 'HoD',
  HEAD_OF_YEAR: 'HoY', SLT: 'SLT', SCHOOL_ADMIN: 'Admin',
}

type Props = {
  plan: EhcpPlanWithOutcomes
  isSenco: boolean
}

export default function EhcpCard({ plan, isSenco }: Props) {
  const [approved,       setApproved]       = useState(plan.approvedBySenco)
  const [approving,      setApproving]      = useState(false)
  const [sectionsOpen,   setSectionsOpen]   = useState(false)
  const [editingSection, setEditingSection] = useState<string | null>(null)
  const [editValue,      setEditValue]      = useState('')
  const [saving,         setSaving]         = useState(false)
  const [sections,       setSections]       = useState<EhcpSections | null>(plan.sections)
  const [auditOpen,      setAuditOpen]      = useState(false)
  const [auditEntries,   setAuditEntries]   = useState<EhcpAuditEntryRow[] | null>(null)
  const [auditLoading,   setAuditLoading]   = useState(false)

  async function handleApprove() {
    setApproving(true)
    try {
      await approveGeneratedEhcp(plan.id)
      setApproved(true)
    } finally {
      setApproving(false)
    }
  }

  function startEdit(key: string) {
    setEditingSection(key)
    setEditValue((sections as any)?.[key] ?? '')
  }

  async function saveSection(key: string) {
    setSaving(true)
    try {
      await updateEhcpSection(plan.id, key as keyof EhcpSections, editValue)
      setSections(prev => prev ? { ...prev, [key]: editValue } : null)
      setEditingSection(null)
    } finally {
      setSaving(false)
    }
  }

  async function handleToggleAudit() {
    if (!auditOpen && auditEntries === null) {
      setAuditLoading(true)
      try {
        const entries = await getEhcpAuditLog(plan.id)
        setAuditEntries(entries)
      } finally {
        setAuditLoading(false)
      }
    }
    setAuditOpen(prev => !prev)
  }

  const isUnderReview = plan.status === 'under_review' && !approved

  return (
    <div className="space-y-4">
      {/* AI draft + approval banner */}
      {plan.autoGenerated && isUnderReview && isSenco && (
        <div className="flex items-center justify-between bg-purple-50 border border-purple-200 rounded-xl px-4 py-3">
          <div className="flex items-center gap-2 text-purple-800 text-sm">
            <Icon name="auto_awesome" size="sm" />
            <span className="font-medium">AI-generated draft</span>
            <span className="text-purple-600">— review all sections before approving</span>
          </div>
          <button
            onClick={handleApprove}
            disabled={approving}
            className="flex items-center gap-1.5 text-xs bg-green-600 text-white px-3 py-1.5 rounded-full hover:bg-green-700 disabled:opacity-50"
          >
            <Icon name="verified_user" size="sm" />
            {approving ? 'Approving…' : 'Approve EHCP'}
          </button>
        </div>
      )}
      {approved && plan.autoGenerated && (
        <div className="flex items-center gap-2 bg-green-50 border border-green-200 rounded-xl px-4 py-2 text-sm text-green-800">
          <Icon name="check_circle" size="sm" /> EHCP approved and active
        </div>
      )}

      {/* Outcome tracker (Section E structured outcomes) */}
      {plan.outcomes.length > 0 && (
        <div>
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Section E — Outcomes</p>
          <EhcpOutcomeTracker plan={plan} />
        </div>
      )}

      {/* Narrative sections collapsible */}
      {sections && (
        <div className="border border-gray-200 rounded-xl overflow-hidden">
          <button
            onClick={() => setSectionsOpen(p => !p)}
            className="w-full flex items-center justify-between px-4 py-3 text-sm font-medium text-gray-700 hover:bg-gray-50"
          >
            <span>View / edit EHCP sections (A–K)</span>
            <Icon name="chevron_right" size="sm" className={`transition-transform ${sectionsOpen ? 'rotate-90' : ''}`} />
          </button>

          {sectionsOpen && (
            <div className="border-t border-gray-100 divide-y divide-gray-100">
              {SECTION_KEYS.map(key => {
                const content = (sections as any)[key] as string ?? ''
                const isEmpty = !content.trim()
                const isEditing = editingSection === key

                return (
                  <div key={key} className="px-4 py-3">
                    <div className="flex items-start justify-between gap-2 mb-1">
                      <p className="text-xs font-semibold text-gray-600">{SECTION_LABELS[key]}</p>
                      {isSenco && !isEditing && key !== 'J' && (
                        <button
                          onClick={() => startEdit(key)}
                          className="shrink-0 flex items-center gap-1 text-xs text-blue-600 hover:text-blue-800"
                        >
                          <Icon name="edit" size="sm" /> Edit
                        </button>
                      )}
                    </div>

                    {isEditing ? (
                      <div className="space-y-2">
                        <textarea
                          value={editValue}
                          onChange={e => setEditValue(e.target.value)}
                          rows={5}
                          className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm resize-y"
                          autoFocus
                        />
                        <div className="flex gap-2">
                          <button
                            onClick={() => saveSection(key)}
                            disabled={saving}
                            className="flex items-center gap-1 text-xs bg-blue-600 text-white px-3 py-1.5 rounded-lg hover:bg-blue-700 disabled:opacity-50"
                          >
                            <Icon name="save" size="sm" /> {saving ? 'Saving…' : 'Save'}
                          </button>
                          <button
                            onClick={() => setEditingSection(null)}
                            className="flex items-center gap-1 text-xs border border-gray-200 px-3 py-1.5 rounded-lg hover:bg-gray-50"
                          >
                            <Icon name="close" size="sm" /> Cancel
                          </button>
                        </div>
                      </div>
                    ) : (
                      <p className={`text-sm ${isEmpty ? 'text-gray-400 italic' : 'text-gray-700'}`}>
                        {isEmpty ? (key === 'J' ? 'Not applicable' : 'Not yet completed') : content}
                      </p>
                    )}
                  </div>
                )
              })}
            </div>
          )}
        </div>
      )}

      {/* Audit trail — only after approval */}
      {approved && (
        <div className="border-t border-gray-100 pt-3">
          <button
            onClick={handleToggleAudit}
            className="flex items-center gap-2 text-xs text-gray-500 hover:text-gray-700 font-medium"
          >
            <Icon name="history" size="sm" />
            {auditOpen ? 'Hide' : 'Show'} edit history
            <Icon name="chevron_right" size="sm" className={`transition-transform ${auditOpen ? 'rotate-90' : ''}`} />
          </button>

          {auditOpen && (
            <div className="mt-3">
              {auditLoading ? (
                <p className="text-xs text-gray-400 animate-pulse">Loading…</p>
              ) : !auditEntries || auditEntries.length === 0 ? (
                <p className="text-xs text-gray-400">No edits recorded yet.</p>
              ) : (
                <ol className="relative border-l border-gray-200 space-y-4 pl-4">
                  {auditEntries.map(entry => (
                    <li key={entry.id} className="relative">
                      <span className="absolute -left-[1.15rem] top-1 w-2 h-2 rounded-full bg-purple-400 border-2 border-white" />
                      <p className="text-xs font-medium text-gray-800">
                        {entry.userName}
                        <span className="font-normal text-gray-500">
                          {' '}({ROLE_LABELS[entry.userRole] ?? entry.userRole})
                        </span>
                        {' '}edited <span className="font-medium">{entry.fieldChanged}</span>
                        {' '}on {new Date(entry.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}
                      </p>
                      {(entry.previousValue || entry.newValue) && (
                        <p className="text-xs text-gray-500 mt-0.5">
                          {entry.changeType === 'ADDED' ? (
                            <>Added: <span className="text-green-700">&ldquo;{entry.newValue.slice(0, 120)}{entry.newValue.length > 120 ? '…' : ''}&rdquo;</span></>
                          ) : entry.changeType === 'DELETED' ? (
                            <>Removed: <span className="text-red-600 line-through">&ldquo;{entry.previousValue.slice(0, 120)}{entry.previousValue.length > 120 ? '…' : ''}&rdquo;</span></>
                          ) : (
                            <>&ldquo;{entry.previousValue.slice(0, 80)}{entry.previousValue.length > 80 ? '…' : ''}&rdquo; → &ldquo;{entry.newValue.slice(0, 80)}{entry.newValue.length > 80 ? '…' : ''}&rdquo;</>
                          )}
                        </p>
                      )}
                    </li>
                  ))}
                </ol>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  )
}
