'use client'

import { useState, useMemo } from 'react'
import Icon from '@/components/ui/Icon'
import type { EhcpPlanWithOutcomes, StudentWithoutEhcp } from '@/app/actions/ehcp'
import EhcpCard from './EhcpCard'

const STATUS_LABEL: Record<string, string> = {
  active: 'Active',
  under_review: 'Under Review',
  ceased: 'Ceased',
}

const STATUS_COLOUR: Record<string, string> = {
  active:       'bg-green-100 text-green-700',
  under_review: 'bg-yellow-100 text-yellow-800',
  ceased:       'bg-gray-100 text-gray-600',
}

function daysUntil(date: Date) {
  return Math.ceil((new Date(date).getTime() - Date.now()) / (1000 * 60 * 60 * 24))
}

type Props = {
  plans: EhcpPlanWithOutcomes[]
  studentsWithoutEhcp: StudentWithoutEhcp[]
  isSenco: boolean
}

export default function EhcpPageClient({ plans, studentsWithoutEhcp, isSenco }: Props) {
  const [expanded,   setExpanded]   = useState<Set<string>>(new Set())
  const [searchQuery, setSearchQuery] = useState('')
  const [yearFilter,  setYearFilter]  = useState('')
  const [viewMode,    setViewMode]    = useState<'plans' | 'no_ehcp'>('plans')

  const aiDrafts   = plans.filter(p => p.autoGenerated && !p.approvedBySenco)
  const overdue     = plans.filter(p => p.approvedBySenco && daysUntil(p.reviewDate) < 0)
  const dueWithin30 = plans.filter(p => { const d = daysUntil(p.reviewDate); return p.approvedBySenco && d >= 0 && d <= 30 })
  const onTrack     = plans.filter(p => p.approvedBySenco && daysUntil(p.reviewDate) > 30)

  // Year options from both plans and students-without-EHCP
  const yearOptions = useMemo(() => {
    const years = new Set([
      ...plans.map(p => p.yearGroup).filter((y): y is number => y != null),
      ...studentsWithoutEhcp.map(s => s.yearGroup).filter((y): y is number => y != null),
    ])
    return [...years].sort((a, b) => a - b)
  }, [plans, studentsWithoutEhcp])

  const filteredPlans = useMemo(() => plans.filter(p => {
    if (yearFilter && p.yearGroup !== Number(yearFilter)) return false
    if (searchQuery) {
      const q = searchQuery.toLowerCase()
      if (!p.studentName.toLowerCase().includes(q)) return false
    }
    return true
  }), [plans, yearFilter, searchQuery])

  const filteredWithoutEhcp = useMemo(() => studentsWithoutEhcp.filter(s => {
    if (yearFilter && s.yearGroup !== Number(yearFilter)) return false
    if (searchQuery) {
      const q = searchQuery.toLowerCase()
      if (!s.studentName.toLowerCase().includes(q)) return false
    }
    return true
  }), [studentsWithoutEhcp, yearFilter, searchQuery])

  function toggleExpand(id: string) {
    setExpanded(prev => {
      const next = new Set(prev)
      next.has(id) ? next.delete(id) : next.add(id)
      return next
    })
  }

  return (
    <div className="space-y-6">
      {/* Summary stats */}
      <div className="grid grid-cols-3 gap-4">
        <div className="bg-red-50 border border-red-200 rounded-xl p-4">
          <div className="flex items-center gap-2 text-red-700 mb-1">
            <Icon name="warning" size="sm" />
            <span className="text-sm font-medium">Review overdue</span>
          </div>
          <div className="text-3xl font-bold text-red-700">{overdue.length}</div>
        </div>
        <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
          <div className="flex items-center gap-2 text-amber-700 mb-1">
            <Icon name="schedule" size="sm" />
            <span className="text-sm font-medium">Due within 30 days</span>
          </div>
          <div className="text-3xl font-bold text-amber-700">{dueWithin30.length}</div>
        </div>
        <div className="bg-green-50 border border-green-200 rounded-xl p-4">
          <div className="flex items-center gap-2 text-green-700 mb-1">
            <Icon name="check_circle" size="sm" />
            <span className="text-sm font-medium">On track</span>
          </div>
          <div className="text-3xl font-bold text-green-700">{onTrack.length}</div>
        </div>
      </div>

      {/* AI drafts banner */}
      {aiDrafts.length > 0 && isSenco && (
        <div className="bg-purple-50 border border-purple-200 rounded-xl p-3 flex items-start gap-2">
          <Icon name="auto_awesome" size="sm" className="text-purple-600 shrink-0 mt-0.5" />
          <p className="text-sm text-purple-800">
            <span className="font-semibold">{aiDrafts.length} AI-generated EHCP draft{aiDrafts.length > 1 ? 's' : ''}</span>
            {' '}awaiting your review and approval below.
          </p>
        </div>
      )}

      {/* UK GDPR notice */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl p-3 flex items-start gap-2">
        <Icon name="warning" size="sm" className="text-amber-600 shrink-0 mt-0.5" />
        <p className="text-xs text-amber-800">
          EHCP data is Special Category under UK GDPR (Article 9). Access is logged. Do not share outside authorised staff.
          All annual reviews also require Local Authority sign-off.
        </p>
      </div>

      {/* Toolbar: view mode + search + year filter */}
      <div className="bg-white border border-gray-200 rounded-xl p-4 space-y-3">
        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={() => setViewMode('plans')}
            className={`px-3 py-1.5 rounded-lg text-[12px] font-medium transition-colors ${viewMode === 'plans' ? 'bg-purple-600 text-white' : 'text-gray-600 hover:bg-gray-100'}`}
          >
            EHCP Plans ({plans.length})
          </button>
          {studentsWithoutEhcp.length > 0 && (
            <button
              onClick={() => setViewMode('no_ehcp')}
              className={`px-3 py-1.5 rounded-lg text-[12px] font-medium transition-colors flex items-center gap-1.5 ${viewMode === 'no_ehcp' ? 'bg-amber-500 text-white' : 'text-amber-700 bg-amber-50 hover:bg-amber-100'}`}
            >
              <Icon name="warning" size="sm" />
              SEND without EHCP ({studentsWithoutEhcp.length})
            </button>
          )}
        </div>
        <div className="flex items-center gap-3">
          <div className="relative flex-1">
            <Icon name="search" size="sm" className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
            <input
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              placeholder="Search by student name…"
              className="w-full pl-8 pr-3 py-2 text-[12px] border border-gray-200 rounded-lg bg-gray-50 focus:outline-none focus:ring-2 focus:ring-purple-300"
            />
          </div>
          <select
            value={yearFilter}
            onChange={e => setYearFilter(e.target.value)}
            className="border border-gray-200 rounded-lg px-2.5 py-2 text-[12px] bg-gray-50 focus:outline-none focus:ring-2 focus:ring-purple-300"
          >
            <option value="">All years</option>
            {yearOptions.map(y => <option key={y} value={y}>Year {y}</option>)}
          </select>
        </div>
      </div>

      {/* SEND without EHCP view */}
      {viewMode === 'no_ehcp' ? (
        filteredWithoutEhcp.length === 0 ? (
          <div className="text-center py-16 text-gray-400">
            <Icon name="check_circle" size="lg" className="mx-auto mb-3 opacity-30" />
            <p className="text-sm">All SEND students have an EHCP plan.</p>
          </div>
        ) : (
          <div className="border border-gray-200 rounded-xl overflow-hidden divide-y divide-gray-100">
            {filteredWithoutEhcp.map(s => (
              <div key={s.id} className="flex items-center gap-3 px-4 py-3 hover:bg-gray-50">
                <div className="flex-1 min-w-0">
                  <p className="text-[13px] font-medium text-gray-900">{s.studentName}</p>
                  <p className="text-[11px] text-gray-500">
                    {s.yearGroup ? `Year ${s.yearGroup}` : ''}
                    {s.yearGroup && s.needArea ? ' · ' : ''}
                    {s.needArea ?? s.sendStatus.replace(/_/g, ' ')}
                  </p>
                </div>
                <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${s.sendStatus === 'EHCP' ? 'bg-purple-100 text-purple-700' : 'bg-blue-100 text-blue-700'}`}>
                  {s.sendStatus === 'EHCP' ? 'EHCP' : 'SEN Support'}
                </span>
                <a
                  href={`/student/${s.id}/send`}
                  className="text-[11px] text-purple-600 hover:underline"
                >
                  View record →
                </a>
              </div>
            ))}
          </div>
        )
      ) : filteredPlans.length === 0 ? (
        <div className="text-center py-16 text-gray-400">
          <Icon name="task_alt" size="lg" className="mx-auto mb-3 opacity-30" />
          <p className="text-sm">{searchQuery || yearFilter ? 'No plans match your search.' : 'No active EHCP plans recorded.'}</p>
        </div>
      ) : (
        <div className="space-y-4">
          {filteredPlans.map(plan => {
            const days = daysUntil(plan.reviewDate)
            const isOverdue  = days < 0
            const isDueSoon  = days >= 0 && days <= 30
            const achieved   = plan.outcomes.filter(o => o.status === 'achieved').length
            const isAiDraft  = plan.autoGenerated && !plan.approvedBySenco
            const isExpanded = expanded.has(plan.id)

            return (
              <div key={plan.id} className={`border rounded-2xl overflow-hidden shadow-sm ${isAiDraft ? 'border-purple-200' : 'border-gray-200'}`}>
                {/* Collapsible header */}
                <button
                  onClick={() => toggleExpand(plan.id)}
                  className={`w-full text-left px-5 py-4 flex items-start justify-between gap-3 ${isAiDraft ? 'bg-purple-50' : isOverdue ? 'bg-red-50' : isDueSoon ? 'bg-amber-50' : 'bg-white'} hover:brightness-95 transition-all`}
                >
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      <h2 className="font-semibold text-gray-900">{plan.studentName}</h2>
                      {plan.yearGroup && (
                        <span className="text-xs text-gray-500 bg-gray-100 px-1.5 py-0.5 rounded">Year {plan.yearGroup}</span>
                      )}
                      {isAiDraft && (
                        <span className="flex items-center gap-1 text-xs bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full">
                          <Icon name="auto_awesome" size="sm" /> AI draft
                        </span>
                      )}
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${isAiDraft ? 'bg-yellow-100 text-yellow-800' : (STATUS_COLOUR[plan.status] ?? 'bg-gray-100 text-gray-600')}`}>
                        {isAiDraft ? 'Needs approval' : (STATUS_LABEL[plan.status] ?? plan.status)}
                      </span>
                    </div>
                    <div className="flex items-center gap-3 text-xs text-gray-500">
                      <span>LA: {plan.localAuthority}</span>
                      <span>·</span>
                      <span>Plan date: {new Date(plan.planDate).toLocaleDateString('en-GB')}</span>
                      {plan.coordinatorName && <><span>·</span><span>Co-ordinator: {plan.coordinatorName}</span></>}
                      {plan.outcomes.length > 0 && (
                        <><span>·</span><span>{achieved}/{plan.outcomes.length} outcomes achieved</span></>
                      )}
                    </div>
                  </div>
                  <div className="flex items-center gap-3 shrink-0">
                    {!isAiDraft && (
                      <div className={`text-sm font-semibold ${isOverdue ? 'text-red-700' : isDueSoon ? 'text-amber-700' : 'text-gray-500'}`}>
                        {isOverdue ? `${Math.abs(days)}d overdue` : `Review in ${days}d`}
                      </div>
                    )}
                    <Icon name={isExpanded ? 'expand_less' : 'expand_more'} size="md" className="text-gray-400" />
                  </div>
                </button>

                {/* Expanded: EhcpCard + footer */}
                {isExpanded && (
                  <>
                    <div className="p-5 border-t border-gray-100 space-y-4">
                      <EhcpCard plan={plan} isSenco={isSenco} />
                    </div>
                    <div className="px-5 py-3 bg-gray-50 border-t border-gray-100">
                      <div className="flex items-center justify-between text-xs text-gray-500">
                        <span>{plan.outcomes.filter(o => o.evidenceCount > 0).length} of {plan.outcomes.length} outcomes have evidence</span>
                        <a href={`/student/${plan.studentId}/send`} className="text-purple-600 hover:underline">
                          View student SEND record →
                        </a>
                      </div>
                    </div>
                  </>
                )}
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
