'use client'

import { useState } from 'react'
import Icon from '@/components/ui/Icon'
import type { EhcpPlanWithOutcomes, EhcpSections, EhcpAuditEntryRow, EhcpAnnualReviewRow } from '@/app/actions/ehcp'
import { approveGeneratedEhcp, updateEhcpSection, getEhcpAuditLog } from '@/app/actions/ehcp'
import EhcpOutcomeTracker from '@/components/homework/EhcpOutcomeTracker'
import EhcpAnnualReviewModal from './EhcpAnnualReviewModal'
import { toast } from '@/components/ui/Toast'

const SECTION_KEYS = ['A','B','C','D','E','F','G','H1','H2','I','J','K'] as const
const SECTION_LABELS: Record<string, string> = {
  A:  'Section A — Views and aspirations of child and parents',
  B:  'Section B — Special educational needs',
  C:  'Section C — Health needs',
  D:  'Section D — Social care needs',
  E:  'Section E — Educational outcomes',
  F:  'Section F — Special educational provision',
  G:  'Section G — Health provision',
  H1: 'Section H1 — Social care provision (local authority)',
  H2: 'Section H2 — Other social care provision',
  I:  'Section I — School placement',
  J:  'Section J — Personal budget',
  K:  'Section K — Appendices',
}

const ROLE_LABELS: Record<string, string> = {
  SENCO: 'SENCO', TEACHER: 'Teacher', HEAD_OF_DEPT: 'HoD',
  HEAD_OF_YEAR: 'HoY', SLT: 'SLT', SCHOOL_ADMIN: 'Admin',
}

const PROGRESS_LABELS: Record<string, string> = {
  GOOD_PROGRESS: 'Good Progress',
  SOME_PROGRESS: 'Some Progress',
  INSUFFICIENT:  'Insufficient Progress',
  NO_PROGRESS:   'No Progress Made',
}

const PROGRESS_COLOURS: Record<string, string> = {
  GOOD_PROGRESS: 'bg-green-100 text-green-800',
  SOME_PROGRESS: 'bg-blue-100 text-blue-800',
  INSUFFICIENT:  'bg-amber-100 text-amber-800',
  NO_PROGRESS:   'bg-red-100 text-red-800',
}

type Props = {
  plan: EhcpPlanWithOutcomes
  isSenco: boolean
}

export default function EhcpCard({ plan, isSenco }: Props) {
  const [approved,            setApproved]            = useState(plan.approvedBySenco)
  const [approving,           setApproving]           = useState(false)
  const [reviewNote,          setReviewNote]          = useState('')
  const [sectionsOpen,        setSectionsOpen]        = useState(false)
  const [editingSection,      setEditingSection]      = useState<string | null>(null)
  const [editValue,           setEditValue]           = useState('')
  const [saving,              setSaving]              = useState(false)
  const [sections,            setSections]            = useState<EhcpSections | null>(plan.sections)
  const [auditOpen,           setAuditOpen]           = useState(false)
  const [auditEntries,        setAuditEntries]        = useState<EhcpAuditEntryRow[] | null>(null)
  const [auditLoading,        setAuditLoading]        = useState(false)
  const [showAnnualReview,    setShowAnnualReview]    = useState(false)
  const [annualReviews,       setAnnualReviews]       = useState<EhcpAnnualReviewRow[]>(plan.annualReviews ?? [])
  const [reviewHistoryOpen,   setReviewHistoryOpen]   = useState(false)

  async function handleApprove() {
    setApproving(true)
    try {
      await approveGeneratedEhcp(plan.id, reviewNote.trim() || undefined)
      setApproved(true)
      toast('EHCP plan approved')
    } catch {
      toast('Failed to approve EHCP plan', 'error')
    } finally {
      setApproving(false)
    }
  }

  function startEdit(key: string) {
    setEditingSection(key)
    setEditValue((sections as any)?.[key] ?? '')
  }

  async function saveSection(key: string) {
    setSaving(true)
    try {
      await updateEhcpSection(plan.id, key as keyof EhcpSections, editValue)
      setSections(prev => prev ? { ...prev, [key]: editValue } : null)
      setEditingSection(null)
      toast('Section saved')
    } catch {
      toast('Failed to save section', 'error')
    } finally {
      setSaving(false)
    }
  }

  async function handleToggleAudit() {
    if (!auditOpen && auditEntries === null) {
      setAuditLoading(true)
      try {
        const entries = await getEhcpAuditLog(plan.id)
        setAuditEntries(entries)
      } finally {
        setAuditLoading(false)
      }
    }
    setAuditOpen(prev => !prev)
  }

  // Show approval banner for any plan not yet signed off by SENCO (regardless of status field)
  const isUnderReview = !approved

  return (
    <>
    <div className="space-y-4">
      {/* Pending approval banner (auto-generated or manual) */}
      {isUnderReview && isSenco && (
        <div className="bg-amber-50 border border-amber-200 rounded-xl px-4 py-3 space-y-3">
          <div className="flex items-center gap-2 text-amber-800 text-sm">
            <Icon name={plan.autoGenerated ? 'auto_awesome' : 'pending'} size="sm" />
            <span className="font-medium">
              {plan.autoGenerated ? 'AI-generated draft' : 'EHCP plan'} — requires SENCO sign-off before outcomes can be tracked
            </span>
          </div>
          <div className="space-y-1.5">
            <label className="text-[11px] font-semibold text-amber-700 uppercase tracking-wide block">
              SENCO review commentary <span className="font-normal text-amber-600">(logged with approval)</span>
            </label>
            <textarea
              value={reviewNote}
              onChange={e => setReviewNote(e.target.value)}
              rows={2}
              placeholder="Summarise your review — e.g. sections reviewed, any amendments made, next steps…"
              className="w-full text-sm border border-amber-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-amber-400 bg-white resize-none"
            />
          </div>
          <button
            onClick={handleApprove}
            disabled={approving}
            className="flex items-center gap-1.5 text-sm font-semibold bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 disabled:opacity-50 transition-colors"
          >
            <Icon name="verified_user" size="sm" />
            {approving ? 'Approving…' : 'Approve & Activate EHCP'}
          </button>
        </div>
      )}
      {approved && (
        <div className="flex items-center gap-2 bg-green-50 border border-green-200 rounded-xl px-4 py-2 text-sm text-green-800">
          <Icon name="check_circle" size="sm" /> EHCP approved and active
        </div>
      )}

      {/* Outcome tracker (Section E structured outcomes) */}
      {plan.outcomes.length > 0 && (
        <div>
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Section E — Outcomes</p>
          <EhcpOutcomeTracker plan={plan} />
        </div>
      )}

      {/* Narrative sections collapsible */}
      {sections && (
        <div className="border border-gray-200 rounded-xl overflow-hidden">
          <button
            onClick={() => setSectionsOpen(p => !p)}
            className="w-full flex items-center justify-between px-4 py-3 text-sm font-medium text-gray-700 hover:bg-gray-50"
          >
            <span>View / edit EHCP sections (A–K)</span>
            <Icon name="chevron_right" size="sm" className={`transition-transform ${sectionsOpen ? 'rotate-90' : ''}`} />
          </button>

          {sectionsOpen && (
            <div className="border-t border-gray-100 divide-y divide-gray-100">
              {SECTION_KEYS.map(key => {
                const content = (sections as any)[key] as string ?? ''
                const isEmpty = !content.trim()
                const isEditing = editingSection === key

                return (
                  <div key={key} className="px-4 py-3">
                    <div className="flex items-start justify-between gap-2 mb-1">
                      <p className="text-xs font-semibold text-gray-600">{SECTION_LABELS[key]}</p>
                      {isSenco && !isEditing && key !== 'J' && (
                        <button
                          onClick={() => startEdit(key)}
                          className="shrink-0 flex items-center gap-1 text-xs text-blue-600 hover:text-blue-800"
                        >
                          <Icon name="edit" size="sm" /> Edit
                        </button>
                      )}
                    </div>

                    {isEditing ? (
                      <div className="space-y-2">
                        <textarea
                          value={editValue}
                          onChange={e => setEditValue(e.target.value)}
                          rows={5}
                          className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm resize-y"
                          autoFocus
                        />
                        <div className="flex gap-2">
                          <button
                            onClick={() => saveSection(key)}
                            disabled={saving}
                            className="flex items-center gap-1 text-xs bg-blue-600 text-white px-3 py-1.5 rounded-lg hover:bg-blue-700 disabled:opacity-50"
                          >
                            <Icon name="save" size="sm" /> {saving ? 'Saving…' : 'Save'}
                          </button>
                          <button
                            onClick={() => setEditingSection(null)}
                            className="flex items-center gap-1 text-xs border border-gray-200 px-3 py-1.5 rounded-lg hover:bg-gray-50"
                          >
                            <Icon name="close" size="sm" /> Cancel
                          </button>
                        </div>
                      </div>
                    ) : (
                      <p className={`text-sm ${isEmpty ? 'text-gray-400 italic' : 'text-gray-700'}`}>
                        {isEmpty ? (key === 'J' ? 'Not applicable' : 'Not yet completed') : content}
                      </p>
                    )}
                  </div>
                )
              })}
            </div>
          )}
        </div>
      )}

      {/* Annual review — available once approved */}
      {approved && isSenco && (
        <div className="border border-purple-100 rounded-xl overflow-hidden">
          <div className="flex items-center justify-between px-4 py-3 bg-purple-50">
            <div className="flex items-center gap-2">
              <Icon name="rate_review" size="sm" className="text-purple-600" />
              <span className="text-[12px] font-semibold text-purple-900">Annual Reviews</span>
              {annualReviews.length > 0 && (
                <span className="text-[10px] bg-purple-200 text-purple-800 px-1.5 py-0.5 rounded-full font-bold">
                  {annualReviews.length}
                </span>
              )}
            </div>
            <div className="flex items-center gap-2">
              {annualReviews.length > 0 && (
                <button
                  onClick={() => setReviewHistoryOpen(p => !p)}
                  className="text-[11px] text-purple-600 hover:text-purple-800 font-medium"
                >
                  {reviewHistoryOpen ? 'Hide history' : 'View history'}
                </button>
              )}
              <button
                onClick={() => setShowAnnualReview(true)}
                className="flex items-center gap-1 text-[11px] font-semibold bg-purple-600 text-white px-3 py-1.5 rounded-lg hover:bg-purple-700 transition-colors"
              >
                <Icon name="add" size="sm" /> Conduct Review
              </button>
            </div>
          </div>

          {reviewHistoryOpen && annualReviews.length > 0 && (
            <div className="divide-y divide-gray-100">
              {annualReviews.map(r => (
                <div key={r.id} className="px-4 py-3 space-y-1.5">
                  <div className="flex items-center justify-between gap-2">
                    <div className="flex items-center gap-2">
                      <span className="text-[12px] font-semibold text-gray-900">
                        {new Date(r.reviewDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}
                      </span>
                      {r.progressRating && (
                        <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${PROGRESS_COLOURS[r.progressRating] ?? 'bg-gray-100 text-gray-600'}`}>
                          {PROGRESS_LABELS[r.progressRating] ?? r.progressRating}
                        </span>
                      )}
                      {r.amendmentsNeeded && (
                        <span className="text-[10px] bg-amber-100 text-amber-700 px-2 py-0.5 rounded-full font-semibold">
                          Amendments needed
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <a
                        href={`/api/export/ehcp-review/${r.id}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center gap-1 text-[11px] text-purple-600 hover:text-purple-800 font-medium"
                      >
                        <Icon name="picture_as_pdf" size="sm" /> PDF
                      </a>
                    </div>
                  </div>
                  <p className="text-[11px] text-gray-600 line-clamp-2">{r.summary}</p>
                  <div className="flex items-center gap-3 text-[10px] text-gray-400">
                    <span>Reviewed by {r.reviewerName}</span>
                    <span>Next review: {new Date(r.newReviewDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}</span>
                    {r.laNotified && <span className="text-green-600">LA notified</span>}
                  </div>
                </div>
              ))}
            </div>
          )}

          {annualReviews.length === 0 && (
            <p className="px-4 py-3 text-[12px] text-gray-400">No annual reviews recorded yet.</p>
          )}
        </div>
      )}

      {/* Annual review — read-only history for non-SENCO staff */}
      {approved && !isSenco && annualReviews.length > 0 && (
        <div className="border border-gray-200 rounded-xl overflow-hidden">
          <button
            onClick={() => setReviewHistoryOpen(p => !p)}
            className="w-full flex items-center justify-between px-4 py-3 text-sm font-medium text-gray-700 hover:bg-gray-50"
          >
            <span className="flex items-center gap-2">
              <Icon name="rate_review" size="sm" className="text-purple-500" />
              Annual Reviews ({annualReviews.length})
            </span>
            <Icon name="chevron_right" size="sm" className={`transition-transform ${reviewHistoryOpen ? 'rotate-90' : ''}`} />
          </button>
          {reviewHistoryOpen && (
            <div className="border-t border-gray-100 divide-y divide-gray-100">
              {annualReviews.map(r => (
                <div key={r.id} className="px-4 py-3 space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[12px] font-semibold text-gray-900">
                      {new Date(r.reviewDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}
                    </span>
                    {r.progressRating && (
                      <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${PROGRESS_COLOURS[r.progressRating] ?? 'bg-gray-100 text-gray-600'}`}>
                        {PROGRESS_LABELS[r.progressRating] ?? r.progressRating}
                      </span>
                    )}
                  </div>
                  <p className="text-[11px] text-gray-600 line-clamp-2">{r.summary}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Audit trail — only after approval */}
      {approved && (
        <div className="border-t border-gray-100 pt-3">
          <button
            onClick={handleToggleAudit}
            className="flex items-center gap-2 text-xs text-gray-500 hover:text-gray-700 font-medium"
          >
            <Icon name="history" size="sm" />
            {auditOpen ? 'Hide' : 'Show'} edit history
            <Icon name="chevron_right" size="sm" className={`transition-transform ${auditOpen ? 'rotate-90' : ''}`} />
          </button>

          {auditOpen && (
            <div className="mt-3">
              {auditLoading ? (
                <p className="text-xs text-gray-400 animate-pulse">Loading…</p>
              ) : !auditEntries || auditEntries.length === 0 ? (
                <p className="text-xs text-gray-400">No edits recorded yet.</p>
              ) : (
                <ol className="relative border-l border-gray-200 space-y-4 pl-4">
                  {auditEntries.map(entry => (
                    <li key={entry.id} className="relative">
                      <span className="absolute -left-[1.15rem] top-1 w-2 h-2 rounded-full bg-purple-400 border-2 border-white" />
                      <p className="text-xs font-medium text-gray-800">
                        {entry.userName}
                        <span className="font-normal text-gray-500">
                          {' '}({ROLE_LABELS[entry.userRole] ?? entry.userRole})
                        </span>
                        {' '}edited <span className="font-medium">{entry.fieldChanged}</span>
                        {' '}on {new Date(entry.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}
                      </p>
                      {(entry.previousValue || entry.newValue) && (
                        <p className="text-xs text-gray-500 mt-0.5">
                          {entry.changeType === 'ADDED' ? (
                            <>Added: <span className="text-green-700">&ldquo;{entry.newValue.slice(0, 120)}{entry.newValue.length > 120 ? '…' : ''}&rdquo;</span></>
                          ) : entry.changeType === 'DELETED' ? (
                            <>Removed: <span className="text-red-600 line-through">&ldquo;{entry.previousValue.slice(0, 120)}{entry.previousValue.length > 120 ? '…' : ''}&rdquo;</span></>
                          ) : (
                            <>&ldquo;{entry.previousValue.slice(0, 80)}{entry.previousValue.length > 80 ? '…' : ''}&rdquo; → &ldquo;{entry.newValue.slice(0, 80)}{entry.newValue.length > 80 ? '…' : ''}&rdquo;</>
                          )}
                        </p>
                      )}
                    </li>
                  ))}
                </ol>
              )}
            </div>
          )}
        </div>
      )}
    </div>

    {showAnnualReview && (
      <EhcpAnnualReviewModal
        ehcpId={plan.id}
        studentName={plan.studentName}
        onClose={() => setShowAnnualReview(false)}
        onCompleted={review => {
          setAnnualReviews(prev => [review, ...prev])
          setReviewHistoryOpen(true)
          setShowAnnualReview(false)
        }}
      />
    )}
    </>
  )
}
