'use client'

import { useState } from 'react'
import { FileHeart, Target, CheckCircle, Clock, XCircle, ChevronDown, Sparkles, ThumbsUp, ThumbsDown, Package, ShieldCheck, History, ChevronRight, Loader2 } from 'lucide-react'
import type { IlpWithTargets, IlpAuditEntryRow } from '@/app/actions/send-support'
import { updateIlpTarget, approveGeneratedIlp, getIlpAuditLog, updateSendStatus } from '@/app/actions/send-support'

const ROLE_LABELS: Record<string, string> = {
  SENCO: 'SENCO', TEACHER: 'Teacher', HEAD_OF_DEPT: 'HoD',
  HEAD_OF_YEAR: 'HoY', SLT: 'SLT', SCHOOL_ADMIN: 'Admin',
}

const TARGET_STATUS_ICONS: Record<string, React.ReactNode> = {
  active:       <Clock size={14} className="text-blue-500" />,
  achieved:     <CheckCircle size={14} className="text-green-500" />,
  not_achieved: <XCircle size={14} className="text-red-500" />,
  deferred:     <ChevronDown size={14} className="text-orange-500" />,
}

type Props = { ilp: IlpWithTargets }

export default function IlpCard({ ilp }: Props) {
  const [updatingId,       setUpdatingId]       = useState<string | null>(null)
  const [expandedTargetId, setExpandedTargetId] = useState<string | null>(null)
  const [notes,            setNotes]            = useState('')
  const [approving,        setApproving]        = useState(false)
  const [approved,         setApproved]         = useState(false)
  const [auditOpen,        setAuditOpen]        = useState(false)
  const [auditEntries,     setAuditEntries]     = useState<IlpAuditEntryRow[] | null>(null)
  const [auditLoading,     setAuditLoading]     = useState(false)
  const [sendStatus,       setSendStatus]       = useState(ilp.sendStatus ?? 'NONE')
  const [statusUpdating,   setStatusUpdating]   = useState(false)
  const [statusToast,      setStatusToast]      = useState<string | null>(null)

  async function handleToggleAudit() {
    if (!auditOpen && auditEntries === null) {
      setAuditLoading(true)
      try {
        const entries = await getIlpAuditLog(ilp.id)
        setAuditEntries(entries)
      } finally {
        setAuditLoading(false)
      }
    }
    setAuditOpen(prev => !prev)
  }

  async function handleApprove() {
    setApproving(true)
    try {
      await approveGeneratedIlp(ilp.id)
      setApproved(true)
    } finally {
      setApproving(false)
    }
  }

  async function handleSendStatusChange(newStatus: 'NONE' | 'SEN_SUPPORT' | 'EHCP') {
    if (newStatus === sendStatus) return
    setStatusUpdating(true)
    try {
      await updateSendStatus(ilp.studentId, newStatus)
      setSendStatus(newStatus)
      const label = newStatus === 'NONE' ? 'No SEND' : newStatus === 'SEN_SUPPORT' ? 'SEN Support' : 'EHCP'
      setStatusToast(`SEND status updated to ${label}`)
      setTimeout(() => setStatusToast(null), 3000)
    } catch {
      setStatusToast('Failed to update SEND status')
      setTimeout(() => setStatusToast(null), 3000)
    } finally {
      setStatusUpdating(false)
    }
  }

  async function saveTargetUpdate(targetId: string, status: string) {
    setUpdatingId(targetId)
    try {
      await updateIlpTarget(targetId, status, notes)
    } finally {
      setUpdatingId(null)
      setExpandedTargetId(null)
      setNotes('')
    }
  }

  const reviewSoon = new Date(ilp.reviewDate).getTime() - Date.now() < 14 * 24 * 60 * 60 * 1000

  return (
    <div className="bg-white border border-gray-200 rounded-2xl overflow-hidden">
      {/* Toast */}
      {statusToast && (
        <div className="px-5 py-2 bg-blue-50 border-b border-blue-100 text-xs text-blue-700 font-medium">
          {statusToast}
        </div>
      )}

      {/* Header */}
      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 px-5 py-4 border-b border-gray-100">
        <div className="flex items-start justify-between gap-3">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <FileHeart size={16} className="text-blue-600" />
              <h3 className="font-semibold text-gray-900">Individual Learning Plan</h3>
              {ilp.autoGenerated && (
                <span className="flex items-center gap-1 text-xs bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full">
                  <Sparkles size={11} /> AI-generated
                </span>
              )}
            </div>
            <p className="text-sm text-gray-600 mb-2">
              {ilp.studentName} · {ilp.sendCategory}
            </p>
            {/* SEND status dropdown */}
            <div className="flex items-center gap-2">
              <label className="text-[10px] font-semibold uppercase tracking-wider text-gray-400">SEND Status</label>
              <div className="relative flex items-center gap-1.5">
                <select
                  value={sendStatus}
                  onChange={e => handleSendStatusChange(e.target.value as 'NONE' | 'SEN_SUPPORT' | 'EHCP')}
                  disabled={statusUpdating}
                  className="text-xs border border-gray-200 rounded-lg px-2 py-1 pr-6 bg-white disabled:opacity-60 focus:outline-none focus:ring-1 focus:ring-blue-300"
                >
                  <option value="NONE">No SEND</option>
                  <option value="SEN_SUPPORT">SEN Support</option>
                  <option value="EHCP">EHCP</option>
                </select>
                {statusUpdating && <Loader2 size={12} className="animate-spin text-blue-500 shrink-0" />}
              </div>
            </div>
          </div>
          <div className="text-right space-y-1">
            <p className={`text-xs font-medium ${reviewSoon ? 'text-orange-600' : 'text-gray-500'}`}>
              Review: {new Date(ilp.reviewDate).toLocaleDateString('en-GB')}
            </p>
            {reviewSoon && <p className="text-xs text-orange-500">Review due soon</p>}
            {ilp.status === 'under_review' && !approved && (
              <button
                onClick={handleApprove}
                disabled={approving}
                className="flex items-center gap-1 text-xs bg-green-600 text-white px-3 py-1 rounded-full hover:bg-green-700 disabled:opacity-50 ml-auto"
              >
                <ShieldCheck size={12} />
                {approving ? 'Approving…' : 'Approve ILP'}
              </button>
            )}
            {approved && (
              <span className="flex items-center gap-1 text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full ml-auto">
                <CheckCircle size={11} /> Approved
              </span>
            )}
          </div>
        </div>
      </div>

      <div className="p-5 space-y-5">
        {/* Strengths & Needs */}
        <div className="grid md:grid-cols-2 gap-4">
          <div>
            <p className="text-xs font-semibold text-green-700 uppercase tracking-wider mb-1">Current Strengths</p>
            <p className="text-sm text-gray-700">{ilp.currentStrengths}</p>
          </div>
          <div>
            <p className="text-xs font-semibold text-amber-700 uppercase tracking-wider mb-1">Areas of Need</p>
            <p className="text-sm text-gray-700">{ilp.areasOfNeed}</p>
          </div>
        </div>

        {/* Targets */}
        <div>
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Targets</p>
          <div className="space-y-2">
            {ilp.targets.map(t => (
              <div key={t.id} className="border border-gray-100 rounded-xl p-3">
                <div className="flex items-start gap-2">
                  {TARGET_STATUS_ICONS[t.status] ?? <Target size={14} className="text-gray-400" />}
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-gray-900">{t.target}</p>
                    <p className="text-xs text-gray-500 mt-0.5">Strategy: {t.strategy}</p>
                    <p className="text-xs text-gray-500">Success measure: {t.successMeasure}</p>
                    {t.progressNotes && (
                      <p className="text-xs text-blue-700 bg-blue-50 rounded px-2 py-1 mt-1">{t.progressNotes}</p>
                    )}
                    <p className="text-xs text-gray-400 mt-1">Target date: {new Date(t.targetDate).toLocaleDateString('en-GB')}</p>
                  </div>
                  <button
                    onClick={() => setExpandedTargetId(expandedTargetId === t.id ? null : t.id)}
                    className="shrink-0 text-xs px-2 py-1 border border-gray-200 rounded-lg hover:bg-gray-50"
                  >
                    Update
                  </button>
                </div>

                {expandedTargetId === t.id && (
                  <div className="mt-3 pt-3 border-t border-gray-100 space-y-2">
                    <select
                      defaultValue={t.status}
                      onChange={e => saveTargetUpdate(t.id, e.target.value)}
                      disabled={updatingId === t.id}
                      className="w-full border border-gray-200 rounded-lg px-2 py-1.5 text-xs"
                    >
                      <option value="active">Active</option>
                      <option value="achieved">Achieved</option>
                      <option value="not_achieved">Not Achieved</option>
                      <option value="deferred">Deferred</option>
                    </select>
                    <textarea
                      value={notes}
                      onChange={e => setNotes(e.target.value)}
                      placeholder="Progress notes (optional)…"
                      rows={2}
                      className="w-full border border-gray-200 rounded-lg px-2 py-1.5 text-xs resize-none"
                    />
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Strategies */}
        {ilp.strategies.length > 0 && (
          <div>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Teaching Strategies</p>
            <ul className="space-y-1">
              {ilp.strategies.map((s, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                  <span className="text-blue-400 mt-0.5">·</span>
                  {s}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* AI-generated: likes / dislikes */}
        {(ilp.likes || ilp.dislikes) && (
          <div className="grid md:grid-cols-2 gap-4">
            {ilp.likes && (
              <div>
                <p className="text-xs font-semibold text-blue-700 uppercase tracking-wider mb-1 flex items-center gap-1">
                  <ThumbsUp size={11} /> What the student enjoys
                </p>
                <p className="text-sm text-gray-700">{ilp.likes}</p>
              </div>
            )}
            {ilp.dislikes && (
              <div>
                <p className="text-xs font-semibold text-rose-700 uppercase tracking-wider mb-1 flex items-center gap-1">
                  <ThumbsDown size={11} /> Common challenges
                </p>
                <p className="text-sm text-gray-700">{ilp.dislikes}</p>
              </div>
            )}
          </div>
        )}

        {/* AI-generated: resources needed */}
        {ilp.resourcesNeeded && ilp.resourcesNeeded.length > 0 && (
          <div>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2 flex items-center gap-1">
              <Package size={11} /> Resources Needed
            </p>
            <ul className="space-y-1">
              {ilp.resourcesNeeded.map((r, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                  <span className="text-purple-400 mt-0.5">·</span>
                  {r}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Success criteria */}
        <div>
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Success Criteria</p>
          <p className="text-sm text-gray-700">{ilp.successCriteria}</p>
        </div>

        {/* Audit trail — only visible once ILP is approved */}
        {ilp.approvedBySenco && (
          <div className="border-t border-gray-100 pt-4">
            <button
              onClick={handleToggleAudit}
              className="flex items-center gap-2 text-xs text-gray-500 hover:text-gray-700 font-medium"
            >
              <History size={13} />
              {auditOpen ? 'Hide' : 'Show'} edit history
              <ChevronRight size={12} className={`transition-transform ${auditOpen ? 'rotate-90' : ''}`} />
            </button>

            {auditOpen && (
              <div className="mt-3">
                {auditLoading ? (
                  <p className="text-xs text-gray-400 animate-pulse">Loading…</p>
                ) : !auditEntries || auditEntries.length === 0 ? (
                  <p className="text-xs text-gray-400">No edits recorded yet.</p>
                ) : (
                  <ol className="relative border-l border-gray-200 space-y-4 pl-4">
                    {auditEntries.map(entry => (
                      <li key={entry.id} className="relative">
                        <span className="absolute -left-[1.15rem] top-1 w-2 h-2 rounded-full bg-blue-400 border-2 border-white" />
                        <p className="text-xs font-medium text-gray-800">
                          {entry.userName}
                          <span className="font-normal text-gray-500">
                            {' '}({ROLE_LABELS[entry.userRole] ?? entry.userRole})
                          </span>
                          {' '}edited <span className="font-medium">{entry.fieldChanged}</span>
                          {' '}on {new Date(entry.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}
                        </p>
                        {entry.previousValue || entry.newValue ? (
                          <p className="text-xs text-gray-500 mt-0.5">
                            {entry.changeType === 'ADDED' ? (
                              <>Added: <span className="text-green-700">&ldquo;{entry.newValue}&rdquo;</span></>
                            ) : entry.changeType === 'DELETED' ? (
                              <>Removed: <span className="text-red-600 line-through">&ldquo;{entry.previousValue}&rdquo;</span></>
                            ) : (
                              <>&ldquo;{entry.previousValue}&rdquo; → &ldquo;{entry.newValue}&rdquo;</>
                            )}
                          </p>
                        ) : null}
                      </li>
                    ))}
                  </ol>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}
