'use server'

import { auth } from '@/lib/auth'
import { redirect } from 'next/navigation'
import { prisma, writeEHCPAudit } from '@/lib/prisma'
import { revalidatePath } from 'next/cache'
import Anthropic from '@anthropic-ai/sdk'

// ─── Guards ───────────────────────────────────────────────────────────────────

async function requireSencoOrStaff() {
  const session = await auth()
  if (!session) redirect('/login')
  const user = session.user as { id: string; schoolId: string; role: string; firstName: string; lastName: string }
  if (!['SENCO', 'SLT', 'SCHOOL_ADMIN', 'HEAD_OF_YEAR', 'TEACHER', 'HEAD_OF_DEPT'].includes(user.role)) {
    redirect('/dashboard')
  }
  return user
}

async function requireSenco() {
  const session = await auth()
  if (!session) redirect('/login')
  const user = session.user as { id: string; schoolId: string; role: string; firstName: string; lastName: string }
  if (!['SENCO', 'SLT', 'SCHOOL_ADMIN'].includes(user.role)) redirect('/dashboard')
  return user
}

// ─── Types ────────────────────────────────────────────────────────────────────

export type EhcpOutcomeInput = {
  section: string
  outcomeText: string
  targetDate: Date
  successCriteria: string
  provisionRequired?: string
}

export type EhcpSections = {
  A: string; B: string; C: string; D: string
  E: string; F: string; G: string; H1: string
  H2: string; I: string; J: string; K: string
}

export type EhcpAuditEntryRow = {
  id: string
  ehcpId: string
  userId: string
  userName: string
  userRole: string
  fieldChanged: string
  previousValue: string
  newValue: string
  changeType: string
  createdAt: Date
}

export type EhcpPlanWithOutcomes = {
  id: string
  schoolId: string
  studentId: string
  studentName: string
  localAuthority: string
  planDate: Date
  reviewDate: Date
  coordinatorName: string | null
  status: string
  autoGenerated: boolean
  approvedBySenco: boolean
  ilpId: string | null
  sections: EhcpSections | null
  createdAt: Date
  outcomes: {
    id: string
    section: string
    outcomeText: string
    targetDate: Date
    successCriteria: string
    provisionRequired: string | null
    status: string
    evidenceCount: number
  }[]
}

// ─── EHCP Plan CRUD ───────────────────────────────────────────────────────────

export async function createEhcpPlan(data: {
  studentId: string
  localAuthority: string
  planDate: Date
  reviewDate: Date
  coordinatorName?: string
  outcomes: EhcpOutcomeInput[]
}): Promise<void> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  // Verify student belongs to this school
  const student = await prisma.user.findFirst({
    where: { id: data.studentId, schoolId, role: 'STUDENT' },
    select: { id: true, firstName: true, lastName: true },
  })
  if (!student) throw new Error('Student not found')

  // Mark any existing active plan as under_review
  await prisma.ehcpPlan.updateMany({
    where: { schoolId, studentId: data.studentId, status: 'active' },
    data: { status: 'under_review' },
  })

  const plan = await prisma.ehcpPlan.create({
    data: {
      schoolId,
      studentId: data.studentId,
      localAuthority: data.localAuthority,
      planDate: data.planDate,
      reviewDate: data.reviewDate,
      coordinatorName: data.coordinatorName ?? null,
      status: 'active',
      createdBy: user.id,
      outcomes: {
        create: data.outcomes.map(o => ({
          section: o.section,
          outcomeText: o.outcomeText,
          targetDate: o.targetDate,
          successCriteria: o.successCriteria,
          provisionRequired: o.provisionRequired ?? null,
        })),
      },
    },
  })

  // Log to SendReviewLog (EHCP is Special Category data)
  await prisma.sendReviewLog.create({
    data: {
      schoolId,
      studentId: data.studentId,
      action: 'ilp_created',
      actorId: user.id,
      metadata: { ehcpId: plan.id, localAuthority: data.localAuthority, type: 'EHCP' },
    },
  })

  // Notify HOY and class teachers
  const [hoys, classTeachers] = await Promise.all([
    prisma.user.findMany({ where: { schoolId, role: 'HEAD_OF_YEAR', isActive: true }, select: { id: true } }),
    prisma.classTeacher.findMany({
      where: { class: { enrolments: { some: { userId: data.studentId } }, schoolId } },
      select: { userId: true },
    }),
  ])
  const notifyIds = [...new Set([...hoys.map(h => h.id), ...classTeachers.map(ct => ct.userId)])]
  const studentName = `${student.firstName} ${student.lastName}`
  if (notifyIds.length > 0) {
    await prisma.sendNotification.createMany({
      data: notifyIds.map(recipientId => ({
        schoolId,
        recipientId,
        type: 'ilp_created',
        title: `EHCP plan recorded: ${studentName}`,
        body: `An EHCP plan has been recorded for ${studentName}. Please review SEND strategies in your planning.`,
      })),
    })
  }

  revalidatePath('/senco/ehcp')
}

export async function getStudentEhcp(studentId: string): Promise<EhcpPlanWithOutcomes | null> {
  const user = await requireSencoOrStaff()
  const schoolId = user.schoolId

  // Log access to EHCP data (Special Category)
  await prisma.sendReviewLog.create({
    data: {
      schoolId,
      studentId,
      action: 'ilp_updated',
      actorId: user.id,
      metadata: { action: 'ehcp_viewed', role: user.role },
    },
  })

  const plan = await prisma.ehcpPlan.findFirst({
    where: { schoolId, studentId, status: { in: ['active', 'under_review'] } },
    include: { outcomes: { orderBy: [{ section: 'asc' }, { targetDate: 'asc' }] } },
    orderBy: { planDate: 'desc' },
  })
  if (!plan) return null

  const student = await prisma.user.findUnique({
    where: { id: studentId },
    select: { firstName: true, lastName: true },
  })

  return {
    id: plan.id,
    schoolId: plan.schoolId,
    studentId: plan.studentId,
    studentName: student ? `${student.firstName} ${student.lastName}` : 'Unknown',
    localAuthority: plan.localAuthority,
    planDate: plan.planDate,
    reviewDate: plan.reviewDate,
    coordinatorName: plan.coordinatorName,
    status: plan.status,
    autoGenerated: plan.autoGenerated,
    approvedBySenco: plan.approvedBySenco,
    ilpId: plan.ilpId,
    sections: plan.sections as EhcpSections | null,
    createdAt: plan.createdAt,
    outcomes: plan.outcomes.map(o => ({
      id: o.id,
      section: o.section,
      outcomeText: o.outcomeText,
      targetDate: o.targetDate,
      successCriteria: o.successCriteria,
      provisionRequired: o.provisionRequired,
      status: o.status,
      evidenceCount: o.evidenceCount,
    })),
  }
}

export async function getAllEhcpPlans(): Promise<EhcpPlanWithOutcomes[]> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  const plans = await prisma.ehcpPlan.findMany({
    where: { schoolId, status: { not: 'ceased' } },
    include: { outcomes: { orderBy: [{ section: 'asc' }] } },
    orderBy: { reviewDate: 'asc' },
  })

  const studentIds = [...new Set(plans.map(p => p.studentId))]
  const students = await prisma.user.findMany({
    where: { id: { in: studentIds } },
    select: { id: true, firstName: true, lastName: true },
  })
  const studentMap = new Map(students.map(s => [s.id, `${s.firstName} ${s.lastName}`]))

  return plans.map(p => ({
    id: p.id,
    schoolId: p.schoolId,
    studentId: p.studentId,
    studentName: studentMap.get(p.studentId) ?? 'Unknown',
    localAuthority: p.localAuthority,
    planDate: p.planDate,
    reviewDate: p.reviewDate,
    coordinatorName: p.coordinatorName,
    status: p.status,
    autoGenerated: p.autoGenerated,
    approvedBySenco: p.approvedBySenco,
    ilpId: p.ilpId,
    sections: p.sections as EhcpSections | null,
    createdAt: p.createdAt,
    outcomes: p.outcomes.map(o => ({
      id: o.id,
      section: o.section,
      outcomeText: o.outcomeText,
      targetDate: o.targetDate,
      successCriteria: o.successCriteria,
      provisionRequired: o.provisionRequired,
      status: o.status,
      evidenceCount: o.evidenceCount,
    })),
  }))
}

// ─── ILP / EHCP Evidence Linking ─────────────────────────────────────────────

export async function linkHomeworkToIlpTarget(
  homeworkId: string,
  ilpTargetId: string,
  evidenceNote?: string,
): Promise<void> {
  const user = await requireSencoOrStaff()
  const schoolId = user.schoolId

  // Verify homework belongs to this school
  const hw = await prisma.homework.findFirst({ where: { id: homeworkId, schoolId } })
  if (!hw) throw new Error('Homework not found')

  await prisma.ilpHomeworkLink.upsert({
    where: { ilpTargetId_homeworkId: { ilpTargetId, homeworkId } },
    update: { evidenceNote: evidenceNote ?? null },
    create: { ilpTargetId, homeworkId, linkedBy: user.id, evidenceNote: evidenceNote ?? null },
  })

  revalidatePath('/senco/ilp-evidence')
}

export async function linkSubmissionToEhcpOutcome(
  submissionId: string,
  outcomeId: string,
  teacherNote: string,
  qualityRating: number,
): Promise<void> {
  const user = await requireSencoOrStaff()
  const schoolId = user.schoolId

  // Verify submission belongs to this school
  const sub = await prisma.submission.findFirst({ where: { id: submissionId, schoolId } })
  if (!sub) throw new Error('Submission not found')

  await prisma.homeworkEhcpEvidence.create({
    data: { outcomeId, submissionId, teacherNote, qualityRating, evidenceDate: new Date() },
  })

  // Increment evidenceCount on outcome
  await prisma.ehcpOutcome.update({
    where: { id: outcomeId },
    data: { evidenceCount: { increment: 1 } },
  })

  revalidatePath('/senco/ehcp')
}

export async function updateEhcpOutcomeStatus(
  outcomeId: string,
  status: string,
): Promise<void> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  // Verify outcome belongs to this school via its plan
  const outcome = await prisma.ehcpOutcome.findFirst({
    where: { id: outcomeId, ehcp: { schoolId } },
    select: { id: true, ehcpId: true },
  })
  if (!outcome) throw new Error('Outcome not found')

  await prisma.ehcpOutcome.update({ where: { id: outcomeId }, data: { status } })
  revalidatePath('/senco/ehcp')
}

// ─── ILP targets due for evidencing ──────────────────────────────────────────

export type IlpTargetDue = {
  targetId: string
  target: string
  strategy: string
  successMeasure: string
  targetDate: Date
  status: string
  studentId: string
  studentName: string
  ilpId: string
  daysUntilDue: number
  evidenceCount: number
}

export async function getIlpTargetsDueForEvidencing(): Promise<IlpTargetDue[]> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  const cutoff = new Date(Date.now() + 28 * 24 * 60 * 60 * 1000)

  const targets = await prisma.ilpTarget.findMany({
    where: {
      ilp: { schoolId, status: 'active' },
      status: 'active',
      targetDate: { lte: cutoff },
    },
    include: { ilp: { include: { targets: false } } },
    orderBy: { targetDate: 'asc' },
    take: 50,
  })

  const studentIds = [...new Set(targets.map(t => t.ilp.studentId))]
  const students = await prisma.user.findMany({
    where: { id: { in: studentIds } },
    select: { id: true, firstName: true, lastName: true },
  })
  const studentMap = new Map(students.map(s => [s.id, `${s.firstName} ${s.lastName}`]))

  // Count ILP homework links per target
  const targetIds = targets.map(t => t.id)
  const links = await prisma.ilpHomeworkLink.findMany({
    where: { ilpTargetId: { in: targetIds } },
    select: { ilpTargetId: true },
  })
  const linkCountMap = new Map<string, number>()
  for (const link of links) {
    linkCountMap.set(link.ilpTargetId, (linkCountMap.get(link.ilpTargetId) ?? 0) + 1)
  }

  const now = Date.now()
  return targets.map(t => ({
    targetId: t.id,
    target: t.target,
    strategy: t.strategy,
    successMeasure: t.successMeasure,
    targetDate: t.targetDate,
    status: t.status,
    studentId: t.ilp.studentId,
    studentName: studentMap.get(t.ilp.studentId) ?? 'Unknown',
    ilpId: t.ilpId,
    daysUntilDue: Math.round((t.targetDate.getTime() - now) / (1000 * 60 * 60 * 24)),
    evidenceCount: linkCountMap.get(t.id) ?? 0,
  }))
}

// ─── AI Progress Reports ──────────────────────────────────────────────────────

export async function generateIlpProgressReport(studentId: string): Promise<string> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  const AI_DISCLAIMER = '⚠️ AI-assisted draft — requires SENCO review before use.\n\n'

  const [student, ilp, recentSubmissions] = await Promise.all([
    prisma.user.findUnique({ where: { id: studentId }, select: { firstName: true, lastName: true, yearGroup: true } }),
    prisma.individualLearningPlan.findFirst({
      where: { schoolId, studentId, status: 'active' },
      include: { targets: true },
    }),
    prisma.submission.findMany({
      where: { studentId, schoolId, submittedAt: { gte: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000) } },
      select: { finalScore: true, status: true, submittedAt: true, homework: { select: { title: true, type: true } } },
      orderBy: { submittedAt: 'desc' },
      take: 20,
    }),
  ])

  if (!student) return AI_DISCLAIMER + 'Student not found.'
  if (!ilp) return AI_DISCLAIMER + 'No active ILP found for this student.'

  const scored = recentSubmissions.filter(s => s.finalScore !== null)
  const avgScore = scored.length > 0 ? Math.round(scored.reduce((a, s) => a + (s.finalScore ?? 0), 0) / scored.length) : null
  const completionRate = recentSubmissions.length > 0
    ? Math.round((recentSubmissions.filter(s => s.status !== 'SUBMITTED' || s.finalScore !== null).length / recentSubmissions.length) * 100)
    : 0

  // Fetch linked homework evidence per ILP target
  const ilpLinks = await prisma.ilpHomeworkLink.findMany({
    where: { ilpTargetId: { in: ilp.targets.map(t => t.id) } },
    include: {
      homework: {
        select: {
          title: true,
          dueAt: true,
          submissions: {
            where: { studentId },
            select: { finalScore: true, feedback: true, submittedAt: true },
            take: 1,
          },
        },
      },
    },
  })

  const evidenceByTarget = new Map<string, string[]>()
  for (const link of ilpLinks) {
    const sub = link.homework.submissions[0]
    const evidenceNote = `"${link.homework.title}" (due ${new Date(link.homework.dueAt).toLocaleDateString('en-GB')})${sub?.finalScore != null ? ` — scored ${sub.finalScore}%` : ''}`
    if (!evidenceByTarget.has(link.ilpTargetId)) {
      evidenceByTarget.set(link.ilpTargetId, [])
    }
    evidenceByTarget.get(link.ilpTargetId)!.push(evidenceNote)
  }

  const targetsSummary = ilp.targets.map(t => {
    const evidence = evidenceByTarget.get(t.id) ?? []
    return `- Target: ${t.target}\n  Strategy: ${t.strategy}\n  Success measure: ${t.successMeasure}\n  Due: ${new Date(t.targetDate).toLocaleDateString('en-GB')}\n  Status: ${t.status}\n  Evidence: ${evidence.length > 0 ? evidence.join('; ') : 'No linked homework evidence yet'}`
  }).join('\n')

  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) return AI_DISCLAIMER + `ILP Progress Report — ${student.firstName} ${student.lastName}\n\n[AI service unavailable — please review targets manually]\n\n${targetsSummary}`

  try {
    const client = new Anthropic({ apiKey })
    const msg = await client.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 1000,
      system: 'You are a UK SENCO writing professional ILP progress reports. Use positive, evidence-based language. Avoid diagnoses. Reference specific targets.',
      messages: [{
        role: 'user',
        content: `Write an ILP progress report for ${student.firstName} ${student.lastName} (Year ${student.yearGroup ?? 'unknown'}).

ILP category: ${ilp.sendCategory}
Review date: ${new Date(ilp.reviewDate).toLocaleDateString('en-GB')}

Targets:
${targetsSummary}

Homework performance (last 90 days): ${recentSubmissions.length} tasks, ${completionRate}% completion rate${avgScore ? `, average score ${avgScore}%` : ''}.

Where evidence exists, reference the specific homework tasks in your report. Where no evidence exists for a target, note this as a gap and recommend action.

Write a structured report covering: (1) Overview and progress summary, (2) Target-by-target review with evidence references, (3) Recommendations for next review period. Keep it professional and concise (400–500 words).`,
      }],
    })
    return AI_DISCLAIMER + (msg.content[0] as any).text.trim()
  } catch {
    return AI_DISCLAIMER + `Unable to generate AI report at this time. Please review the targets manually:\n\n${targetsSummary}`
  }
}

export async function generateEhcpAnnualReview(studentId: string): Promise<string> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  const AI_DISCLAIMER = '⚠️ AI-assisted draft — requires SENCO and LA review before use.\n\n'

  const [student, ehcp] = await Promise.all([
    prisma.user.findUnique({ where: { id: studentId }, select: { firstName: true, lastName: true, yearGroup: true } }),
    prisma.ehcpPlan.findFirst({
      where: { schoolId, studentId, status: 'active' },
      include: {
        outcomes: {
          include: {
            evidence: {
              include: {
                submission: {
                  select: {
                    finalScore: true,
                    homework: { select: { title: true, dueAt: true } },
                  },
                },
              },
            },
          },
          orderBy: [{ section: 'asc' }],
        },
      },
    }),
  ])

  if (!student) return AI_DISCLAIMER + 'Student not found.'
  if (!ehcp) return AI_DISCLAIMER + 'No active EHCP found for this student.'

  const outcomesSummary = ehcp.outcomes.map(o =>
    `Section ${o.section}: ${o.outcomeText}\nStatus: ${o.status}\nEvidence pieces: ${o.evidenceCount}\n${o.evidence.map(e => {
      const hwTitle = (e.submission as any)?.homework?.title
      const score = (e.submission as any)?.finalScore
      const dueDate = (e.submission as any)?.homework?.dueAt
      return `  - ${e.teacherNote ?? 'No note'} (quality: ${e.qualityRating ?? 'N/A'}/5)${hwTitle ? ` — from "${hwTitle}"${dueDate ? ` due ${new Date(dueDate).toLocaleDateString('en-GB')}` : ''}` : ''}${score != null ? ` — scored ${score}%` : ''}`
    }).join('\n')}`
  ).join('\n\n')

  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) return AI_DISCLAIMER + `EHCP Annual Review — ${student.firstName} ${student.lastName}\n\n[AI service unavailable]\n\n${outcomesSummary}`

  try {
    const client = new Anthropic({ apiKey })
    const msg = await client.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 1200,
      system: 'You are a UK SENCO writing EHCP annual review reports. Use formal, evidence-based language appropriate for an official local authority document. Structure clearly by outcome.',
      messages: [{
        role: 'user',
        content: `Write an EHCP annual review for ${student.firstName} ${student.lastName} (Year ${student.yearGroup ?? 'unknown'}).

Local Authority: ${ehcp.localAuthority}
Plan date: ${new Date(ehcp.planDate).toLocaleDateString('en-GB')}
Review date: ${new Date(ehcp.reviewDate).toLocaleDateString('en-GB')}

Outcomes and evidence:
${outcomesSummary}

Where evidence exists, reference the specific homework tasks and scores in your review. Where outcomes have no evidence, note this as a gap requiring action before the review meeting.

Write a formal annual review covering: (1) Overview of the year, (2) Review of each outcome with evidence referenced, (3) Recommendations for the coming year. Use appropriate EHCP annual review language (500–700 words).`,
      }],
    })
    return AI_DISCLAIMER + (msg.content[0] as any).text.trim()
  } catch {
    return AI_DISCLAIMER + `Unable to generate AI review at this time.\n\n${outcomesSummary}`
  }
}

// ─── Auto-generation from ILP escalation ─────────────────────────────────────

const SECTION_LABELS: Record<string, string> = {
  A: 'Views and aspirations of child and parents',
  B: 'Special educational needs',
  C: 'Health needs',
  D: 'Social care needs',
  E: 'Educational outcomes',
  F: 'Special educational provision',
  G: 'Health provision',
  H1: 'Social care provision (local authority)',
  H2: 'Other social care provision',
  I:  'School placement',
  J:  'Personal budget',
  K:  'Appendices',
}

function buildEhcpPrompt(
  firstName: string,
  lastName: string,
  yearGroup: number,
  sendCategory: string,
  ilp: {
    currentStrengths: string
    areasOfNeed: string
    strategies: string[]
    successCriteria: string
    likes: string | null
    dislikes: string | null
    targets: { target: string; strategy: string; successMeasure: string }[]
  },
  schoolName: string,
): string {
  const ksLabel = yearGroup <= 9 ? 'KS3' : yearGroup <= 11 ? 'KS4 (GCSE)' : 'KS5 (A-Level)'
  const targetLines = ilp.targets.map((t, i) =>
    `  ${i + 1}. ${t.target} — strategy: ${t.strategy} — success: ${t.successMeasure}`
  ).join('\n')

  return `Generate a UK Education, Health and Care (EHC) Plan for this student.
This plan was escalated from SEN Support to EHCP status.

Student: ${firstName} ${lastName}
Year: Year ${yearGroup} (${ksLabel})
School: ${schoolName}
SEND category: ${sendCategory}

Source ILP data:
Strengths: ${ilp.currentStrengths}
Areas of need: ${ilp.areasOfNeed}
Strategies: ${ilp.strategies.join('; ')}
Success criteria: ${ilp.successCriteria}
${ilp.likes ? `Student enjoys: ${ilp.likes}` : ''}
${ilp.dislikes ? `Common challenges: ${ilp.dislikes}` : ''}
SMART Targets:
${targetLines}

Return ONLY valid JSON (no markdown, no explanation):
{
  "A": "2-3 sentences: views and aspirations of ${firstName} and their parents/carers based on the ILP profile",
  "B": "3-4 sentences: description of special educational needs based on ILP diagnosis, needs, and category",
  "C": "2 sentences: any health needs that affect learning (generic if unknown)",
  "D": "2 sentences: social care needs or note that none are currently identified",
  "E": "2-3 sentences: overall educational outcomes narrative derived from the ILP SMART targets",
  "E_outcomes": [
    {"outcomeText": "SMART outcome 1 derived from ILP target 1", "targetDateWeeks": 52, "successCriteria": "measurable outcome", "provisionRequired": "specific provision"},
    {"outcomeText": "SMART outcome 2 derived from ILP target 2", "targetDateWeeks": 52, "successCriteria": "measurable outcome", "provisionRequired": "specific provision"},
    {"outcomeText": "SMART outcome 3 derived from ILP target 3", "targetDateWeeks": 52, "successCriteria": "measurable outcome", "provisionRequired": "specific provision"}
  ],
  "F": "4-5 sentences: detailed special educational provision plan derived from ILP strategies, specifying frequency, duration, and responsible staff",
  "G": "2 sentences: recommended health provision (e.g. speech and language therapy, OT) if applicable",
  "H1": "1 sentence: local authority social care provision or note none identified",
  "H2": "1 sentence: other social care provision or note none identified",
  "I": "School placement: ${schoolName} (mainstream secondary with SEND support)",
  "J": "",
  "K": "Appendices: 1. ILP (source document); 2. Parental views (pending); 3. Educational Psychology report (pending if required)"
}`
}

/**
 * Called automatically when a student is escalated SEN_SUPPORT → EHCP.
 * Fetches the student's approved ILP and generates a full EHCP via Claude Sonnet.
 * Exported so it can be called directly by SENCO if needed.
 */
export async function generateEHCPFromILP(
  studentId: string,
  triggeredByUserId: string,
): Promise<{ success: boolean; error?: string }> {
  try {
    const apiKey = process.env.ANTHROPIC_API_KEY
    if (!apiKey) return { success: false, error: 'ANTHROPIC_API_KEY not configured' }

    const [student, existingEhcp] = await Promise.all([
      prisma.user.findUnique({
        where: { id: studentId },
        select: {
          id: true, firstName: true, lastName: true, yearGroup: true, schoolId: true,
          school: { select: { name: true } },
          sendStatus: { select: { needArea: true } },
        },
      }),
      prisma.ehcpPlan.findFirst({
        where: {
          studentId,
          status: { in: ['active', 'under_review'] },
        },
        select: { id: true },
      }),
    ])

    if (!student) return { success: false, error: 'Student not found' }

    // Don't overwrite an existing active/under_review EHCP
    if (existingEhcp) return { success: true } // silently skip — plan already exists

    const ilp = await prisma.individualLearningPlan.findFirst({
      where: { schoolId: student.schoolId, studentId, approvedBySenco: true, status: 'active' },
      include: { targets: { where: { status: 'active' } } },
      orderBy: { createdAt: 'desc' },
    })

    if (!ilp) {
      // No approved ILP — create a skeleton EHCP with placeholder sections
      const skeleton: EhcpSections = {
        A: 'Views and aspirations to be completed with student and parents/carers.',
        B: `${student.sendStatus?.needArea ?? 'General learning support'} — full assessment required.`,
        C: 'Health needs assessment pending.',
        D: 'Social care needs assessment pending.',
        E: 'Educational outcomes to be agreed at EHCP planning meeting.',
        F: 'Special educational provision to be specified following EHCP needs assessment.',
        G: 'Health provision to be confirmed by health professionals.',
        H1: 'Local authority social care provision to be confirmed.',
        H2: 'Other social care provision to be confirmed.',
        I: `${student.school.name} (mainstream secondary with SEND support)`,
        J: '',
        K: 'Appendices: 1. Parental views (pending); 2. Educational Psychology report (pending)',
      }

      await prisma.ehcpPlan.create({
        data: {
          schoolId:       student.schoolId,
          studentId,
          localAuthority: 'Pending — to be completed',
          planDate:       new Date(),
          reviewDate:     new Date(Date.now() + 52 * 7 * 24 * 60 * 60 * 1000),
          status:         'under_review',
          createdBy:      triggeredByUserId,
          autoGenerated:  true,
          approvedBySenco: false,
          sections:       skeleton,
        },
      })

      revalidatePath('/senco/ehcp')
      return { success: true }
    }

    // Build prompt and call Claude Sonnet
    const prompt = buildEhcpPrompt(
      student.firstName, student.lastName,
      student.yearGroup ?? 9,
      student.sendStatus?.needArea ?? ilp.sendCategory,
      ilp,
      student.school.name,
    )

    const client = new Anthropic({ apiKey })
    const msg = await client.messages.create({
      model:      'claude-sonnet-4-6',
      max_tokens: 2000,
      system:     'You are a UK SENCO creating an Education, Health and Care Plan. Return ONLY valid JSON, no markdown.',
      messages:   [{ role: 'user', content: prompt }],
    })

    const raw   = (msg.content[0] as { type: string; text: string }).text.trim()
    const match = raw.match(/\{[\s\S]*\}/)
    if (!match) return { success: false, error: 'No JSON in Claude response' }

    const gen = JSON.parse(match[0])

    const sections: EhcpSections = {
      A: String(gen.A ?? ''), B: String(gen.B ?? ''), C: String(gen.C ?? ''),
      D: String(gen.D ?? ''), E: String(gen.E ?? ''), F: String(gen.F ?? ''),
      G: String(gen.G ?? ''), H1: String(gen.H1 ?? ''), H2: String(gen.H2 ?? ''),
      I: String(gen.I  ?? ''), J: '', K: String(gen.K ?? ''),
    }

    // Section E outcomes → structured EhcpOutcome rows
    const eOutcomes: { outcomeText: string; targetDateWeeks: number; successCriteria: string; provisionRequired: string }[] =
      Array.isArray(gen.E_outcomes) ? gen.E_outcomes.slice(0, 5).map((o: Record<string, unknown>) => ({
        outcomeText:       String(o.outcomeText ?? ''),
        targetDateWeeks:   Number(o.targetDateWeeks) || 52,
        successCriteria:   String(o.successCriteria ?? ''),
        provisionRequired: String(o.provisionRequired ?? ''),
      })) : []

    await prisma.ehcpPlan.create({
      data: {
        schoolId:        student.schoolId,
        studentId,
        localAuthority:  'Pending — to be confirmed with LA',
        planDate:        new Date(),
        reviewDate:      new Date(Date.now() + 52 * 7 * 24 * 60 * 60 * 1000),
        status:          'under_review',
        createdBy:       triggeredByUserId,
        autoGenerated:   true,
        approvedBySenco: false,
        ilpId:           ilp.id,
        sections,
        outcomes: {
          create: eOutcomes.map(o => ({
            section:           'E',
            outcomeText:       o.outcomeText,
            targetDate:        new Date(Date.now() + o.targetDateWeeks * 7 * 24 * 60 * 60 * 1000),
            successCriteria:   o.successCriteria,
            provisionRequired: o.provisionRequired || null,
          })),
        },
      },
    })

    // Notify SENCO (self) so they can review the draft
    const sencosInSchool = await prisma.user.findMany({
      where: { schoolId: student.schoolId, role: 'SENCO', isActive: true },
      select: { id: true },
    })
    if (sencosInSchool.length > 0) {
      await prisma.sendNotification.createMany({
        data: sencosInSchool.map(s => ({
          schoolId: student.schoolId,
          recipientId: s.id,
          type: 'ilp_created',
          title: `AI EHCP draft ready: ${student.firstName} ${student.lastName}`,
          body: `An Education, Health and Care Plan has been auto-generated for ${student.firstName} ${student.lastName} from their approved ILP. Please review, edit sections and approve at /senco/ehcp.`,
        })),
      })
    }

    revalidatePath('/senco/ehcp')

    // Auto-generate APDR from ILP (now that EHCP is in place)
    const { generateAPDRForStudent } = await import('./send-support')
    void generateAPDRForStudent(studentId).catch(err =>
      console.error('[generateEHCPFromILP] generateAPDRForStudent failed:', err)
    )

    return { success: true }
  } catch (err) {
    console.error('[generateEHCPFromILP]', err)
    return { success: false, error: String(err).slice(0, 200) }
  }
}

// ─── EHCP Approval & Section Editing ─────────────────────────────────────────

/** Approve a SENCO-reviewed auto-generated EHCP — makes it visible to teachers. */
export async function approveGeneratedEhcp(ehcpId: string): Promise<void> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  const plan = await prisma.ehcpPlan.findFirst({
    where: { id: ehcpId, schoolId },
    select: { id: true, studentId: true },
  })
  if (!plan) throw new Error('EHCP plan not found')

  await prisma.ehcpPlan.update({
    where: { id: ehcpId },
    data: {
      status:          'active',
      approvedBySenco: true,
      approvedAt:      new Date(),
      approvedBy:      user.id,
    },
  })

  // Notify class teachers + HoY
  const [classTeachers, hoys, student] = await Promise.all([
    prisma.classTeacher.findMany({
      where: { class: { enrolments: { some: { userId: plan.studentId } }, schoolId } },
      select: { userId: true },
    }),
    prisma.user.findMany({
      where: { schoolId, role: 'HEAD_OF_YEAR', isActive: true },
      select: { id: true },
    }),
    prisma.user.findUnique({
      where: { id: plan.studentId },
      select: { firstName: true, lastName: true },
    }),
  ])
  const studentName = student ? `${student.firstName} ${student.lastName}` : 'a student'
  const notifyIds = [...new Set([...classTeachers.map(t => t.userId), ...hoys.map(h => h.id)])]

  if (notifyIds.length > 0) {
    await prisma.sendNotification.createMany({
      data: notifyIds.map(recipientId => ({
        schoolId,
        recipientId,
        type: 'ilp_created',
        title: `EHCP approved: ${studentName}`,
        body: `An Education, Health and Care Plan for ${studentName} has been approved. Please review EHCP provision details in your lesson planning.`,
      })),
    })
  }

  revalidatePath('/senco/ehcp')
}

/**
 * Update a single narrative section of an EHCP.
 * Audited only after the EHCP has been approved.
 */
export async function updateEhcpSection(
  ehcpId: string,
  sectionKey: keyof EhcpSections,
  newContent: string,
): Promise<void> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  const plan = await prisma.ehcpPlan.findFirst({
    where: { id: ehcpId, schoolId },
    select: { sections: true, approvedBySenco: true },
  })
  if (!plan) throw new Error('EHCP plan not found')

  const currentSections = (plan.sections ?? {}) as Record<string, string>
  const previousContent = currentSections[sectionKey] ?? ''

  await prisma.ehcpPlan.update({
    where: { id: ehcpId },
    data: { sections: { ...currentSections, [sectionKey]: newContent } },
  })

  if (plan.approvedBySenco && previousContent !== newContent) {
    await writeEHCPAudit({
      ehcpId,
      userId:        user.id,
      userName:      `${user.firstName} ${user.lastName}`,
      userRole:      user.role,
      fieldChanged:  `Section ${sectionKey} — ${SECTION_LABELS[sectionKey] ?? sectionKey}`,
      previousValue: previousContent,
      newValue:      newContent,
      changeType:    !previousContent && newContent ? 'ADDED' : !newContent ? 'DELETED' : 'EDITED',
    })
  }

  revalidatePath('/senco/ehcp')
}

/**
 * Returns audit entries for a given EHCP plan.
 * SENCO/SLT/SCHOOL_ADMIN see all; TEACHER/HOD/HOY see only their own.
 */
export async function getEhcpAuditLog(ehcpId: string): Promise<EhcpAuditEntryRow[]> {
  const user = await requireSencoOrStaff()

  const fullAccess = ['SENCO', 'SLT', 'SCHOOL_ADMIN'].includes(user.role)

  const entries = await prisma.ehcpAuditEntry.findMany({
    where: {
      ehcpId,
      ...(fullAccess ? {} : { userId: user.id }),
    },
    orderBy: { createdAt: 'desc' },
  })

  return entries.map(e => ({
    id:            e.id,
    ehcpId:        e.ehcpId,
    userId:        e.userId,
    userName:      e.userName,
    userRole:      e.userRole,
    fieldChanged:  e.fieldChanged,
    previousValue: e.previousValue,
    newValue:      e.newValue,
    changeType:    e.changeType,
    createdAt:     e.createdAt,
  }))
}
