'use server'

import { auth } from '@/lib/auth'
import { redirect } from 'next/navigation'
import { prisma, writeILPAudit, writeAPDRAudit } from '@/lib/prisma'
import { revalidatePath } from 'next/cache'
import { analyseStudentPatterns } from '@/lib/send/early-warning'
import { analyseConcernPattern } from '@/lib/send/concern-analyser'
import { z } from 'zod'
import Anthropic from '@anthropic-ai/sdk'

// ─── Types ────────────────────────────────────────────────────────────────────

export type ConcernRow = {
  id: string
  studentId: string
  studentName: string
  studentAvatarUrl: string | null
  raisedBy: string
  raiserName: string
  source: string
  category: string
  description: string
  evidenceNotes: string | null
  status: string
  aiAnalysis: string | null
  createdAt: Date
  reviewedAt: Date | null
  reviewNotes: string | null
}

export type IlpWithTargets = {
  id: string
  studentId: string
  studentName: string
  sendCategory: string
  currentStrengths: string
  areasOfNeed: string
  targets: {
    id: string
    target: string
    strategy: string
    successMeasure: string
    targetDate: Date
    status: string
    progressNotes: string | null
  }[]
  strategies: string[]
  successCriteria: string
  reviewDate: Date
  status: string
  parentConsent: boolean
  autoGenerated: boolean
  approvedBySenco: boolean
  likes: string | null
  dislikes: string | null
  resourcesNeeded: string[]
  createdAt: Date
}

export type IlpAuditEntryRow = {
  id: string
  ilpId: string
  userId: string
  userName: string
  userRole: string
  fieldChanged: string
  previousValue: string
  newValue: string
  changeType: string
  createdAt: Date
}

export type ApdrRow = {
  id: string
  studentId: string
  schoolId: string
  cycleNumber: number
  assessContent: string
  planContent: string
  doContent: string
  reviewContent: string
  status: string
  reviewDate: Date
  createdBy: string
  approvedBySenco: boolean
  approvedAt: Date | null
  approvedBy: string | null
  createdAt: Date
  updatedAt: Date
}

export type ApdrAuditEntryRow = {
  id: string
  apdrId: string
  userId: string
  userName: string
  userRole: string
  fieldChanged: string
  previousValue: string
  newValue: string
  changeType: string
  createdAt: Date
}

export type LearnerPassportRow = {
  id: string
  studentId: string
  schoolId: string
  ilpId: string | null
  ehcpId: string | null
  apdrId: string | null
  sendInformation: string
  teacherActions: string[]
  studentCommitments: string[]
  status: string
  approvedBy: string | null
  approvedAt: Date | null
  generatedAt: Date
  createdAt: Date
  updatedAt: Date
}

export type SendNotificationRow = {
  id: string
  type: string
  title: string
  body: string
  isRead: boolean
  createdAt: Date
  concernId: string | null
}

export type EarlyWarningFlagRow = {
  id: string
  studentId: string
  studentName: string
  flagType: string
  severity: string
  description: string
  dataPoints: unknown
  isActioned: boolean
  createdAt: Date
  expiresAt: Date
}

export type SencoDashboardData = {
  openConcerns: number
  highSeverityFlags: number
  studentsWithIlp: number
  ilpReviewsDue: number
  recentConcerns: ConcernRow[]
  activeFlags: EarlyWarningFlagRow[]
}

// ─── Guards ───────────────────────────────────────────────────────────────────

async function requireAuth() {
  const session = await auth()
  if (!session) redirect('/login')
  return session.user as {
    id: string; schoolId: string; role: string; firstName: string; lastName: string
  }
}

async function requireSenco() {
  const user = await requireAuth()
  if (!['SENCO', 'SLT', 'SCHOOL_ADMIN', 'HEAD_OF_YEAR'].includes(user.role)) redirect('/dashboard')
  return user
}

async function requireSencoOnly() {
  const user = await requireAuth()
  if (!['SENCO'].includes(user.role)) redirect('/dashboard')
  return user
}

// ─── Zod schemas ──────────────────────────────────────────────────────────────

const CONCERN_CATEGORIES = [
  'literacy', 'numeracy', 'behaviour', 'attendance',
  'social_emotional', 'communication', 'physical', 'sensory', 'other',
] as const

const RaiseConcernSchema = z.object({
  studentId:     z.string().min(1),
  category:      z.enum(CONCERN_CATEGORIES, { error: 'Invalid category' }),
  description:   z.string().min(10, 'Please provide at least 10 characters').max(1000),
  evidenceNotes: z.string().max(500).optional(),
})

const IlpTargetSchema = z.object({
  target:         z.string().min(5).max(500),
  strategy:       z.string().min(5).max(500),
  successMeasure: z.string().min(5).max(500),
  targetDate:     z.date(),
})

const CreateIlpSchema = z.object({
  studentId:        z.string().min(1),
  sendCategory:     z.string().min(1).max(100),
  currentStrengths: z.string().min(10).max(1000),
  areasOfNeed:      z.string().min(10).max(1000),
  targets:          z.array(IlpTargetSchema).min(1).max(5),
  strategies:       z.array(z.string().max(200)).max(20),
  successCriteria:  z.string().min(10).max(500),
  reviewDate:       z.date(),
})

// ─── Concern Management ───────────────────────────────────────────────────────

export async function raiseConcern(data: {
  studentId: string
  category: string
  description: string
  evidenceNotes?: string
}): Promise<void> {
  const user = await requireAuth()
  if (!['TEACHER', 'HEAD_OF_DEPT', 'HEAD_OF_YEAR', 'SENCO', 'SLT', 'SCHOOL_ADMIN', 'COVER_MANAGER'].includes(user.role)) {
    redirect('/dashboard')
  }

  const validated = RaiseConcernSchema.parse(data)
  const schoolId = user.schoolId

  const concern = await prisma.sendConcern.create({
    data: {
      schoolId,
      studentId: validated.studentId,
      raisedBy: user.id,
      source: 'teacher',
      category: validated.category,
      description: validated.description,
      evidenceNotes: validated.evidenceNotes ?? null,
    },
  })

  await prisma.sendReviewLog.create({
    data: {
      schoolId,
      studentId: validated.studentId,
      action: 'concern_raised',
      actorId: user.id,
      metadata: { concernId: concern.id, category: validated.category },
    },
  })

  // Notify all SENCOs
  const sencos = await prisma.user.findMany({
    where: { schoolId, role: 'SENCO', isActive: true },
    select: { id: true },
  })

  const student = await prisma.user.findUnique({
    where: { id: validated.studentId },
    select: { firstName: true, lastName: true },
  })

  const studentName = student ? `${student.firstName} ${student.lastName}` : 'a student'

  if (sencos.length > 0) {
    await prisma.sendNotification.createMany({
      data: sencos.map(s => ({
        schoolId,
        recipientId: s.id,
        concernId: concern.id,
        type: 'new_concern',
        title: `New SEND concern raised`,
        body: `${user.firstName} ${user.lastName} raised a concern about ${studentName} (${validated.category}).`,
      })),
    })
  }

  // Check if student has 2+ open concerns — if so, also notify HOY
  const openCount = await prisma.sendConcern.count({
    where: { schoolId, studentId: validated.studentId, status: { in: ['open', 'under_review'] } },
  })

  if (openCount >= 3) {
    const hoys = await prisma.user.findMany({
      where: { schoolId, role: 'HEAD_OF_YEAR', isActive: true },
      select: { id: true },
    })
    if (hoys.length > 0) {
      await prisma.sendNotification.createMany({
        data: hoys.map(h => ({
          schoolId,
          recipientId: h.id,
          concernId: concern.id,
          type: 'concern_escalated',
          title: `Multiple SEND concerns: ${studentName}`,
          body: `${studentName} now has ${openCount} open SEND concerns. SENCO has been notified.`,
        })),
      })
    }
  }

  revalidatePath('/senco/concerns')
}

export async function getStudentConcerns(studentId: string): Promise<ConcernRow[]> {
  const user = await requireAuth()
  const allowedRoles = ['SENCO', 'SLT', 'SCHOOL_ADMIN', 'HEAD_OF_YEAR', 'TEACHER', 'HEAD_OF_DEPT', 'COVER_MANAGER']
  if (!allowedRoles.includes(user.role)) redirect('/dashboard')

  const schoolId = user.schoolId

  const concerns = await prisma.sendConcern.findMany({
    where: { schoolId, studentId },
    orderBy: { createdAt: 'desc' },
  })

  const userIds = [...new Set([
    ...concerns.map(c => c.studentId),
    ...concerns.map(c => c.raisedBy),
  ])]

  const users = await prisma.user.findMany({
    where: { id: { in: userIds } },
    select: { id: true, firstName: true, lastName: true, avatarUrl: true },
  })
  const userMap = new Map(users.map(u => [u.id, { name: `${u.firstName} ${u.lastName}`, avatarUrl: u.avatarUrl ?? null }]))

  return concerns.map(c => ({
    id: c.id,
    studentId: c.studentId,
    studentName: userMap.get(c.studentId)?.name ?? 'Unknown',
    studentAvatarUrl: userMap.get(c.studentId)?.avatarUrl ?? null,
    raisedBy: c.raisedBy,
    raiserName: userMap.get(c.raisedBy)?.name ?? 'Unknown',
    source: c.source,
    category: c.category,
    description: c.description,
    evidenceNotes: c.evidenceNotes,
    status: c.status,
    aiAnalysis: c.aiAnalysis,
    createdAt: c.createdAt,
    reviewedAt: c.reviewedAt,
    reviewNotes: c.reviewNotes,
  }))
}

export async function getAllConcerns(filter?: {
  status?: string; category?: string
}): Promise<ConcernRow[]> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  const where: Record<string, unknown> = { schoolId }
  if (filter?.status) where.status = filter.status
  if (filter?.category) where.category = filter.category

  const concerns = await prisma.sendConcern.findMany({
    where,
    orderBy: { createdAt: 'desc' },
    take: 100,
  })

  const userIds = [...new Set([
    ...concerns.map(c => c.studentId),
    ...concerns.map(c => c.raisedBy),
  ])]

  const users = await prisma.user.findMany({
    where: { id: { in: userIds } },
    select: { id: true, firstName: true, lastName: true, avatarUrl: true },
  })
  const userMap = new Map(users.map(u => [u.id, { name: `${u.firstName} ${u.lastName}`, avatarUrl: u.avatarUrl ?? null }]))

  return concerns.map(c => ({
    id: c.id,
    studentId: c.studentId,
    studentName: userMap.get(c.studentId)?.name ?? 'Unknown',
    studentAvatarUrl: userMap.get(c.studentId)?.avatarUrl ?? null,
    raisedBy: c.raisedBy,
    raiserName: userMap.get(c.raisedBy)?.name ?? 'Unknown',
    source: c.source,
    category: c.category,
    description: c.description,
    evidenceNotes: c.evidenceNotes,
    status: c.status,
    aiAnalysis: c.aiAnalysis,
    createdAt: c.createdAt,
    reviewedAt: c.reviewedAt,
    reviewNotes: c.reviewNotes,
  }))
}

export async function reviewConcern(
  concernId: string,
  status: string,
  reviewNotes: string,
): Promise<void> {
  const user = await requireSencoOnly()
  const schoolId = user.schoolId

  const concern = await prisma.sendConcern.findFirst({ where: { id: concernId, schoolId } })
  if (!concern) throw new Error('Concern not found')

  await prisma.sendConcern.update({
    where: { id: concernId },
    data: {
      status,
      reviewedBy: user.id,
      reviewedAt: new Date(),
      reviewNotes,
    },
  })

  await prisma.sendReviewLog.create({
    data: {
      schoolId,
      studentId: concern.studentId,
      action: 'concern_reviewed',
      actorId: user.id,
      metadata: { concernId, status, reviewNotes: reviewNotes.slice(0, 200) },
    },
  })

  if (status === 'escalated') {
    const sltHoy = await prisma.user.findMany({
      where: { schoolId, role: { in: ['SLT', 'HEAD_OF_YEAR'] }, isActive: true },
      select: { id: true },
    })
    if (sltHoy.length > 0) {
      const student = await prisma.user.findUnique({
        where: { id: concern.studentId },
        select: { firstName: true, lastName: true },
      })
      const studentName = student ? `${student.firstName} ${student.lastName}` : 'a student'
      await prisma.sendNotification.createMany({
        data: sltHoy.map(u => ({
          schoolId,
          recipientId: u.id,
          concernId,
          type: 'concern_escalated',
          title: `SEND concern escalated: ${studentName}`,
          body: `SENCO has escalated a ${concern.category} concern about ${studentName}. Review notes: ${reviewNotes.slice(0, 150)}`,
        })),
      })
    }
  }

  revalidatePath('/senco/concerns')
}

export async function requestAiAnalysis(concernId: string): Promise<string> {
  const user = await requireSencoOnly()
  const schoolId = user.schoolId

  const concern = await prisma.sendConcern.findFirst({ where: { id: concernId, schoolId } })
  if (!concern) throw new Error('Concern not found')

  const analysis = await analyseConcernPattern(concern.studentId, schoolId)

  await prisma.sendConcern.update({
    where: { id: concernId },
    data: { aiAnalysis: analysis },
  })

  revalidatePath('/senco/concerns')
  return analysis
}

// ─── ILP Management ───────────────────────────────────────────────────────────

export async function createIlp(data: {
  studentId: string
  sendCategory: string
  currentStrengths: string
  areasOfNeed: string
  targets: { target: string; strategy: string; successMeasure: string; targetDate: Date }[]
  strategies: string[]
  successCriteria: string
  reviewDate: Date
}): Promise<void> {
  const user = await requireSencoOnly()
  const schoolId = user.schoolId

  const validated = CreateIlpSchema.parse(data)

  // Archive any existing active ILPs for this student
  await prisma.individualLearningPlan.updateMany({
    where: { schoolId, studentId: validated.studentId, status: 'active' },
    data: { status: 'archived' },
  })

  const ilp = await prisma.individualLearningPlan.create({
    data: {
      schoolId,
      studentId: validated.studentId,
      createdBy: user.id,
      sendCategory: validated.sendCategory,
      currentStrengths: validated.currentStrengths,
      areasOfNeed: validated.areasOfNeed,
      strategies: validated.strategies,
      successCriteria: validated.successCriteria,
      reviewDate: validated.reviewDate,
      targets: {
        create: validated.targets.map(t => ({
          target: t.target,
          strategy: t.strategy,
          successMeasure: t.successMeasure,
          targetDate: t.targetDate,
        })),
      },
    },
  })

  await prisma.sendReviewLog.create({
    data: {
      schoolId,
      studentId: validated.studentId,
      action: 'ilp_created',
      actorId: user.id,
      metadata: { ilpId: ilp.id, sendCategory: validated.sendCategory },
    },
  })

  // Notify teachers of the student + HOY
  const classTeachers = await prisma.classTeacher.findMany({
    where: {
      class: {
        enrolments: { some: { userId: validated.studentId } },
        schoolId,
      },
    },
    select: { userId: true },
  })

  const hoys = await prisma.user.findMany({
    where: { schoolId, role: 'HEAD_OF_YEAR', isActive: true },
    select: { id: true },
  })

  const notifyIds = [...new Set([
    ...classTeachers.map(ct => ct.userId),
    ...hoys.map(h => h.id),
  ])]

  const student = await prisma.user.findUnique({
    where: { id: validated.studentId },
    select: { firstName: true, lastName: true },
  })
  const studentName = student ? `${student.firstName} ${student.lastName}` : 'a student'

  if (notifyIds.length > 0) {
    await prisma.sendNotification.createMany({
      data: notifyIds.map(recipientId => ({
        schoolId,
        recipientId,
        type: 'ilp_created',
        title: `ILP created: ${studentName}`,
        body: `A new Individual Learning Plan has been created for ${studentName} (${validated.sendCategory}). Please review SEND strategies in your lesson planning.`,
      })),
    })
  }

  revalidatePath('/senco/ilp')
}

export async function getStudentIlp(studentId: string): Promise<IlpWithTargets | null> {
  const user = await requireAuth()
  const allowedRoles = ['SENCO', 'SLT', 'SCHOOL_ADMIN', 'HEAD_OF_YEAR', 'TEACHER', 'HEAD_OF_DEPT']
  if (!allowedRoles.includes(user.role)) redirect('/dashboard')

  const ilp = await prisma.individualLearningPlan.findFirst({
    where: { schoolId: user.schoolId, studentId, status: 'active' },
    include: { targets: { orderBy: { targetDate: 'asc' } } },
  })
  if (!ilp) return null

  const student = await prisma.user.findUnique({
    where: { id: studentId },
    select: { firstName: true, lastName: true },
  })

  return {
    id: ilp.id,
    studentId: ilp.studentId,
    studentName: student ? `${student.firstName} ${student.lastName}` : 'Unknown',
    sendCategory: ilp.sendCategory,
    currentStrengths: ilp.currentStrengths,
    areasOfNeed: ilp.areasOfNeed,
    targets: ilp.targets.map(t => ({
      id: t.id,
      target: t.target,
      strategy: t.strategy,
      successMeasure: t.successMeasure,
      targetDate: t.targetDate,
      status: t.status,
      progressNotes: t.progressNotes,
    })),
    strategies: ilp.strategies,
    successCriteria: ilp.successCriteria,
    reviewDate: ilp.reviewDate,
    status: ilp.status,
    parentConsent: ilp.parentConsent,
    autoGenerated: ilp.autoGenerated,
    approvedBySenco: ilp.approvedBySenco,
    likes: ilp.likes,
    dislikes: ilp.dislikes,
    resourcesNeeded: ilp.resourcesNeeded,
    createdAt: ilp.createdAt,
  }
}

export async function getAllIlps(): Promise<IlpWithTargets[]> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  const ilps = await prisma.individualLearningPlan.findMany({
    where: { schoolId, status: { not: 'archived' } },
    include: { targets: { orderBy: { targetDate: 'asc' } } },
    orderBy: { reviewDate: 'asc' },
  })

  const studentIds = [...new Set(ilps.map(i => i.studentId))]
  const students = await prisma.user.findMany({
    where: { id: { in: studentIds } },
    select: { id: true, firstName: true, lastName: true },
  })
  const studentMap = new Map(students.map(s => [s.id, `${s.firstName} ${s.lastName}`]))

  return ilps.map(ilp => ({
    id: ilp.id,
    studentId: ilp.studentId,
    studentName: studentMap.get(ilp.studentId) ?? 'Unknown',
    sendCategory: ilp.sendCategory,
    currentStrengths: ilp.currentStrengths,
    areasOfNeed: ilp.areasOfNeed,
    targets: ilp.targets.map(t => ({
      id: t.id,
      target: t.target,
      strategy: t.strategy,
      successMeasure: t.successMeasure,
      targetDate: t.targetDate,
      status: t.status,
      progressNotes: t.progressNotes,
    })),
    strategies: ilp.strategies,
    successCriteria: ilp.successCriteria,
    reviewDate: ilp.reviewDate,
    status: ilp.status,
    parentConsent: ilp.parentConsent,
    autoGenerated: ilp.autoGenerated,
    approvedBySenco: ilp.approvedBySenco,
    likes: ilp.likes,
    dislikes: ilp.dislikes,
    resourcesNeeded: ilp.resourcesNeeded,
    createdAt: ilp.createdAt,
  }))
}

export async function updateIlpTarget(
  targetId: string,
  status: string,
  progressNotes: string,
): Promise<void> {
  const user = await requireAuth()
  const allowedRoles = ['SENCO', 'TEACHER', 'HEAD_OF_DEPT', 'HEAD_OF_YEAR', 'SLT', 'SCHOOL_ADMIN']
  if (!allowedRoles.includes(user.role)) redirect('/dashboard')

  // Fetch current values before update for audit comparison
  const current = await prisma.ilpTarget.findUnique({
    where: { id: targetId },
    select: {
      status: true,
      progressNotes: true,
      ilpId: true,
      ilp: { select: { approvedBySenco: true } },
    },
  })

  await prisma.ilpTarget.update({
    where: { id: targetId },
    data: { status, progressNotes, reviewedAt: new Date() },
  })

  // Audit trail — only after SENCO approval
  if (current?.ilp.approvedBySenco) {
    const ilpId   = current.ilpId
    const userName = `${user.firstName} ${user.lastName}`
    const pending: Parameters<typeof writeILPAudit>[0][] = []

    if (current.status !== status) {
      pending.push({
        ilpId, userId: user.id, userName, userRole: user.role,
        fieldChanged: 'Target status',
        previousValue: current.status,
        newValue: status,
        changeType: 'EDITED',
      })
    }
    const prevNotes = current.progressNotes ?? ''
    const nextNotes = progressNotes ?? ''
    if (prevNotes !== nextNotes) {
      pending.push({
        ilpId, userId: user.id, userName, userRole: user.role,
        fieldChanged: 'Target progress notes',
        previousValue: prevNotes,
        newValue: nextNotes,
        changeType: !prevNotes && nextNotes ? 'ADDED' : !nextNotes ? 'DELETED' : 'EDITED',
      })
    }

    if (pending.length > 0) {
      await Promise.all(pending.map(writeILPAudit))
    }
  }

  revalidatePath('/senco/ilp')
}

export async function scheduleIlpReview(ilpId: string, reviewDate: Date): Promise<void> {
  const user = await requireSencoOnly()
  const schoolId = user.schoolId

  const ilp = await prisma.individualLearningPlan.findFirst({
    where: { id: ilpId, schoolId },
    select: { reviewDate: true, approvedBySenco: true, studentId: true },
  })
  if (!ilp) throw new Error('ILP not found')

  await prisma.individualLearningPlan.update({
    where: { id: ilpId },
    data: { reviewDate },
  })

  // Audit trail — only after SENCO approval
  if (ilp.approvedBySenco) {
    await writeILPAudit({
      ilpId,
      userId:        user.id,
      userName:      `${user.firstName} ${user.lastName}`,
      userRole:      user.role,
      fieldChanged:  'Review date',
      previousValue: ilp.reviewDate.toLocaleDateString('en-GB'),
      newValue:      reviewDate.toLocaleDateString('en-GB'),
      changeType:    'EDITED',
    })
  }

  const student = await prisma.user.findUnique({
    where: { id: ilp.studentId },
    select: { firstName: true, lastName: true },
  })
  const studentName = student ? `${student.firstName} ${student.lastName}` : 'student'

  // Notify self (SENCO) 7 days before review
  const reminderDate = new Date(reviewDate)
  reminderDate.setDate(reminderDate.getDate() - 7)

  await prisma.sendNotification.create({
    data: {
      schoolId,
      recipientId: user.id,
      type: 'ilp_review_due',
      title: `ILP review due: ${studentName}`,
      body: `Reminder: ILP review for ${studentName} is scheduled for ${reviewDate.toLocaleDateString('en-GB')}.`,
    },
  })

  revalidatePath('/senco/ilp')
}

// ─── ILP Audit Log ────────────────────────────────────────────────────────────

/**
 * Returns audit entries for a given ILP.
 * SENCO / SCHOOL_ADMIN / SLT see all entries.
 * Teachers / HOD / HOY see only their own entries.
 */
export async function getIlpAuditLog(ilpId: string): Promise<IlpAuditEntryRow[]> {
  const user = await requireAuth()
  const allowedRoles = ['SENCO', 'TEACHER', 'HEAD_OF_DEPT', 'HEAD_OF_YEAR', 'SLT', 'SCHOOL_ADMIN']
  if (!allowedRoles.includes(user.role)) return []

  const fullAccess = ['SENCO', 'SLT', 'SCHOOL_ADMIN'].includes(user.role)

  const entries = await prisma.ilpAuditEntry.findMany({
    where: {
      ilpId,
      ...(fullAccess ? {} : { userId: user.id }),
    },
    orderBy: { createdAt: 'desc' },
  })

  return entries.map(e => ({
    id:            e.id,
    ilpId:         e.ilpId,
    userId:        e.userId,
    userName:      e.userName,
    userRole:      e.userRole,
    fieldChanged:  e.fieldChanged,
    previousValue: e.previousValue,
    newValue:      e.newValue,
    changeType:    e.changeType,
    createdAt:     e.createdAt,
  }))
}

// ─── SEND Status Management ───────────────────────────────────────────────────

/**
 * Updates a student's SendStatus.activeStatus.
 * If transitioning SEN_SUPPORT → EHCP, fires generateEHCPFromILP asynchronously.
 */
export async function updateSendStatus(
  studentId: string,
  newStatus: 'NONE' | 'SEN_SUPPORT' | 'EHCP',
  needArea?: string,
): Promise<void> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  // Verify student belongs to this school
  const student = await prisma.user.findFirst({
    where: { id: studentId, schoolId, role: 'STUDENT' },
    select: { id: true, firstName: true, lastName: true },
  })
  if (!student) throw new Error('Student not found')

  const existing = await prisma.sendStatus.findUnique({
    where: { studentId },
    select: { activeStatus: true },
  })
  const previousStatus = existing?.activeStatus ?? 'NONE'

  await prisma.sendStatus.upsert({
    where: { studentId },
    update: {
      activeStatus: newStatus as any,
      ...(needArea !== undefined ? { needArea } : {}),
    },
    create: {
      studentId,
      activeStatus: newStatus as any,
      needArea: needArea ?? null,
    },
  })

  await prisma.sendReviewLog.create({
    data: {
      schoolId,
      studentId,
      action: 'send_status_changed',
      actorId: user.id,
      metadata: { from: previousStatus, to: newStatus },
    },
  })

  // When escalating SEN_SUPPORT → EHCP, auto-generate an EHCP from the approved ILP
  if (previousStatus === 'SEN_SUPPORT' && newStatus === 'EHCP') {
    const { generateEHCPFromILP } = await import('./ehcp')
    void generateEHCPFromILP(studentId, user.id).catch(err =>
      console.error('[updateSendStatus] generateEHCPFromILP failed:', err)
    )
  }

  revalidatePath('/senco/concerns')
  revalidatePath('/senco/ehcp')
}

// ─── Notifications ────────────────────────────────────────────────────────────

export async function getMyNotifications(): Promise<SendNotificationRow[]> {
  const user = await requireAuth()
  return prisma.sendNotification.findMany({
    where: { recipientId: user.id },
    orderBy: { createdAt: 'desc' },
    take: 30,
  })
}

export async function markNotificationRead(notificationId: string): Promise<void> {
  const user = await requireAuth()
  await prisma.sendNotification.updateMany({
    where: { id: notificationId, recipientId: user.id },
    data: { isRead: true },
  })
}

export async function markAllNotificationsRead(): Promise<void> {
  const user = await requireAuth()
  await prisma.sendNotification.updateMany({
    where: { recipientId: user.id, isRead: false },
    data: { isRead: true },
  })
}

export async function getUnreadCount(): Promise<number> {
  const user = await requireAuth()
  return prisma.sendNotification.count({
    where: { recipientId: user.id, isRead: false },
  })
}

// ─── Early Warning ────────────────────────────────────────────────────────────

export async function getEarlyWarningFlags(): Promise<EarlyWarningFlagRow[]> {
  const user = await requireSenco()
  const schoolId = user.schoolId
  const now = new Date()

  const flags = await prisma.earlyWarningFlag.findMany({
    where: { schoolId, isActioned: false, expiresAt: { gte: now } },
    orderBy: [{ severity: 'desc' }, { createdAt: 'desc' }],
    take: 50,
  })

  const studentIds = [...new Set(flags.map(f => f.studentId))]
  const students = await prisma.user.findMany({
    where: { id: { in: studentIds } },
    select: { id: true, firstName: true, lastName: true },
  })
  const studentMap = new Map(students.map(s => [s.id, `${s.firstName} ${s.lastName}`]))

  return flags.map(f => ({
    id: f.id,
    studentId: f.studentId,
    studentName: studentMap.get(f.studentId) ?? 'Unknown',
    flagType: f.flagType,
    severity: f.severity,
    description: f.description,
    dataPoints: f.dataPoints,
    isActioned: f.isActioned,
    createdAt: f.createdAt,
    expiresAt: f.expiresAt,
  }))
}

export async function actionFlag(flagId: string, notes: string): Promise<void> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  const flag = await prisma.earlyWarningFlag.findFirst({ where: { id: flagId, schoolId } })
  if (!flag) throw new Error('Flag not found')

  await prisma.earlyWarningFlag.update({
    where: { id: flagId },
    data: { isActioned: true, actionedBy: user.id, actionedAt: new Date() },
  })

  await prisma.sendReviewLog.create({
    data: {
      schoolId,
      studentId: flag.studentId,
      action: 'concern_reviewed',
      actorId: user.id,
      metadata: { flagId, flagType: flag.flagType, notes: notes.slice(0, 200) },
    },
  })

  revalidatePath('/senco/early-warning')
}

export async function triggerEarlyWarningAnalysis(): Promise<{ flagsCreated: number }> {
  const user = await requireSenco()
  const flagsCreated = await analyseStudentPatterns(user.schoolId)
  revalidatePath('/senco/early-warning')
  return { flagsCreated }
}

// ─── SENCO Dashboard ──────────────────────────────────────────────────────────

export async function getSencoDashboardData(): Promise<SencoDashboardData> {
  const user = await requireSenco()
  const schoolId = user.schoolId
  const now = new Date()
  const in14Days = new Date(now)
  in14Days.setDate(now.getDate() + 14)

  const [
    openConcerns,
    highSeverityFlags,
    studentsWithIlp,
    ilpReviewsDue,
    recentConcernsRaw,
    activeFlagsRaw,
  ] = await Promise.all([
    prisma.sendConcern.count({ where: { schoolId, status: { in: ['open', 'under_review'] } } }),
    prisma.earlyWarningFlag.count({ where: { schoolId, severity: 'high', isActioned: false, expiresAt: { gte: now } } }),
    prisma.individualLearningPlan.count({ where: { schoolId, status: 'active' } }),
    prisma.individualLearningPlan.count({ where: { schoolId, status: 'active', reviewDate: { gte: now, lte: in14Days } } }),
    prisma.sendConcern.findMany({
      where: { schoolId },
      orderBy: { createdAt: 'desc' },
      take: 5,
    }),
    prisma.earlyWarningFlag.findMany({
      where: { schoolId, isActioned: false, expiresAt: { gte: now } },
      orderBy: [{ severity: 'desc' }, { createdAt: 'desc' }],
      take: 5,
    }),
  ])

  const userIds = [...new Set([
    ...recentConcernsRaw.map(c => c.studentId),
    ...recentConcernsRaw.map(c => c.raisedBy),
    ...activeFlagsRaw.map(f => f.studentId),
  ])]
  const users = await prisma.user.findMany({
    where: { id: { in: userIds } },
    select: { id: true, firstName: true, lastName: true, avatarUrl: true },
  })
  const userMap = new Map(users.map(u => [u.id, { name: `${u.firstName} ${u.lastName}`, avatarUrl: u.avatarUrl ?? null }]))

  return {
    openConcerns,
    highSeverityFlags,
    studentsWithIlp,
    ilpReviewsDue,
    recentConcerns: recentConcernsRaw.map(c => ({
      id: c.id,
      studentId: c.studentId,
      studentName: userMap.get(c.studentId)?.name ?? 'Unknown',
      studentAvatarUrl: userMap.get(c.studentId)?.avatarUrl ?? null,
      raisedBy: c.raisedBy,
      raiserName: userMap.get(c.raisedBy)?.name ?? 'Unknown',
      source: c.source,
      category: c.category,
      description: c.description,
      evidenceNotes: c.evidenceNotes,
      status: c.status,
      aiAnalysis: c.aiAnalysis,
      createdAt: c.createdAt,
      reviewedAt: c.reviewedAt,
      reviewNotes: c.reviewNotes,
    })),
    activeFlags: activeFlagsRaw.map(f => ({
      id: f.id,
      studentId: f.studentId,
      studentName: userMap.get(f.studentId)?.name ?? 'Unknown',
      flagType: f.flagType,
      severity: f.severity,
      description: f.description,
      dataPoints: f.dataPoints,
      isActioned: f.isActioned,
      createdAt: f.createdAt,
      expiresAt: f.expiresAt,
    })),
  }
}

// ─── Student SEND overview (for teacher lesson views) ────────────────────────

export type StudentSendSummary = {
  userId: string
  name: string
  hasSendStatus: boolean
  sendStatus: string | null
  openConcerns: number
  hasActiveIlp: boolean
  ilpStrategies: string[]
  hasWarningFlag: boolean
}

export async function getClassSendSummaries(classId: string): Promise<StudentSendSummary[]> {
  const user = await requireAuth()
  const allowedRoles = ['TEACHER', 'HEAD_OF_DEPT', 'HEAD_OF_YEAR', 'SENCO', 'SLT', 'SCHOOL_ADMIN', 'COVER_MANAGER']
  if (!allowedRoles.includes(user.role)) return []

  const schoolId = user.schoolId
  const now = new Date()

  // Get students in this class
  const enrolments = await prisma.enrolment.findMany({
    where: { classId, class: { schoolId } },
    include: { user: { select: { id: true, firstName: true, lastName: true } } },
  })

  const studentIds = enrolments.map(e => e.userId)
  if (studentIds.length === 0) return []

  const [sendStatuses, openConcernCounts, activeIlps, warningFlags] = await Promise.all([
    prisma.sendStatus.findMany({
      where: { studentId: { in: studentIds } },
      select: { studentId: true, activeStatus: true },
    }),
    prisma.sendConcern.groupBy({
      by: ['studentId'],
      where: { schoolId, studentId: { in: studentIds }, status: { in: ['open', 'under_review'] } },
      _count: { id: true },
    }),
    prisma.individualLearningPlan.findMany({
      where: { schoolId, studentId: { in: studentIds }, status: 'active' },
      select: { studentId: true, strategies: true },
    }),
    prisma.earlyWarningFlag.findMany({
      where: { schoolId, studentId: { in: studentIds }, isActioned: false, expiresAt: { gte: now } },
      select: { studentId: true },
    }),
  ])

  const statusMap = new Map(sendStatuses.map(s => [s.studentId, s.activeStatus as string]))
  const concernMap = new Map(openConcernCounts.map(c => [c.studentId, c._count.id]))
  const ilpMap = new Map(activeIlps.map(i => [i.studentId, i.strategies]))
  const flagSet = new Set(warningFlags.map(f => f.studentId))

  return enrolments.map(e => {
    const sendStatus = statusMap.get(e.userId) ?? null
    return {
      userId: e.userId,
      name: `${e.user.firstName} ${e.user.lastName}`,
      hasSendStatus: sendStatus !== null && sendStatus !== 'NONE',
      sendStatus,
      openConcerns: concernMap.get(e.userId) ?? 0,
      hasActiveIlp: ilpMap.has(e.userId),
      ilpStrategies: ilpMap.get(e.userId) ?? [],
      hasWarningFlag: flagSet.has(e.userId),
    }
  })
}

// ─── ILP auto-generation ─────────────────────────────────────────────────────

function buildIlpPrompt(
  firstName: string,
  lastName: string,
  yearGroup: number,
  sendCategory: string,
): string {
  const ksLabel = yearGroup <= 9 ? 'KS3' : yearGroup <= 11 ? 'KS4 (GCSE)' : 'KS5 (A-Level)'
  return `Generate a UK secondary school Individual Learning Plan for this student.

Student: ${firstName} ${lastName}
Year: Year ${yearGroup} (${ksLabel})
Support category: ${sendCategory}

Return ONLY valid JSON (no markdown):
{
  "likes": "2 sentences describing what Year ${yearGroup} students typically enjoy at school",
  "dislikes": "2 sentences describing common learning challenges for Year ${yearGroup} students",
  "currentStrengths": "2-3 sentences: expected academic strengths at ${ksLabel} level",
  "areasOfNeed": "2-3 sentences: priority development areas based on ${ksLabel} National Curriculum",
  "targets": [
    {"target": "SMART literacy target for Year ${yearGroup}", "strategy": "specific classroom strategy", "successMeasure": "measurable outcome", "targetDateWeeks": 12},
    {"target": "SMART numeracy target for Year ${yearGroup}", "strategy": "specific classroom strategy", "successMeasure": "measurable outcome", "targetDateWeeks": 12},
    {"target": "SMART study-skills/metacognition target", "strategy": "specific classroom strategy", "successMeasure": "measurable outcome", "targetDateWeeks": 12}
  ],
  "strategies": ["strategy 1", "strategy 2", "strategy 3", "strategy 4", "strategy 5"],
  "resourcesNeeded": ["resource 1", "resource 2", "resource 3"],
  "successCriteria": "Overall ILP success measure for the term"
}`
}

/** Generate a single student's ILP draft using Claude. SENCO-only. */
export async function generateILPForStudent(studentId: string): Promise<{ success: boolean; error?: string }> {
  const user = await requireSencoOnly()
  const schoolId = user.schoolId
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) return { success: false, error: 'ANTHROPIC_API_KEY not configured' }

  // Skip if an active or under_review ILP already exists
  const existing = await prisma.individualLearningPlan.findFirst({
    where: { schoolId, studentId, status: { in: ['active', 'under_review'] } },
  })
  if (existing) return { success: false, error: 'ILP already exists for this student' }

  const student = await prisma.user.findFirst({
    where: { id: studentId, schoolId, role: 'STUDENT' },
    select: { id: true, firstName: true, lastName: true, yearGroup: true },
  })
  if (!student) return { success: false, error: 'Student not found' }

  const sendStatus = await prisma.sendStatus.findUnique({
    where: { studentId },
    select: { needArea: true },
  })
  const sendCategory = sendStatus?.needArea ?? 'General Learning Support'
  const yearGroup = student.yearGroup ?? 9

  try {
    const client = new Anthropic({ apiKey })
    const msg = await client.messages.create({
      model:      'claude-haiku-4-5-20251001',
      max_tokens: 1200,
      system:     'You are a UK SENCO creating Individual Learning Plans. Return ONLY valid JSON, no markdown.',
      messages: [{ role: 'user', content: buildIlpPrompt(student.firstName, student.lastName, yearGroup, sendCategory) }],
    })

    const raw   = (msg.content[0] as { type: string; text: string }).text.trim()
    const match = raw.match(/\{[\s\S]*\}/)
    if (!match) return { success: false, error: 'AI did not return valid JSON' }
    const gen = JSON.parse(match[0])

    const twelveWeeks = new Date(Date.now() + 12 * 7 * 24 * 60 * 60 * 1000)
    const thirteenWeeks = new Date(Date.now() + 13 * 7 * 24 * 60 * 60 * 1000)

    await prisma.individualLearningPlan.create({
      data: {
        schoolId,
        studentId,
        createdBy:       user.id,
        sendCategory,
        currentStrengths: String(gen.currentStrengths ?? ''),
        areasOfNeed:      String(gen.areasOfNeed ?? ''),
        strategies:       Array.isArray(gen.strategies) ? gen.strategies.map(String) : [],
        successCriteria:  String(gen.successCriteria ?? ''),
        reviewDate:       thirteenWeeks,
        autoGenerated:    true,
        approvedBySenco:  false,
        likes:            gen.likes ? String(gen.likes) : null,
        dislikes:         gen.dislikes ? String(gen.dislikes) : null,
        resourcesNeeded:  Array.isArray(gen.resourcesNeeded) ? gen.resourcesNeeded.map(String) : [],
        status:           'under_review',
        targets: {
          create: (Array.isArray(gen.targets) ? gen.targets : []).slice(0, 3).map((t: Record<string, unknown>) => ({
            target:         String(t.target ?? ''),
            strategy:       String(t.strategy ?? ''),
            successMeasure: String(t.successMeasure ?? ''),
            targetDate:     new Date(Date.now() + ((Number(t.targetDateWeeks) || 12)) * 7 * 24 * 60 * 60 * 1000),
          })),
        },
      },
    })

    revalidatePath('/senco/ilp')
    return { success: true }
  } catch (err) {
    return { success: false, error: String(err).slice(0, 200) }
  }
}

/** Approve a SENCO-reviewed auto-generated ILP — makes it visible to teachers. */
export async function approveGeneratedIlp(ilpId: string): Promise<void> {
  const user = await requireSencoOnly()
  const schoolId = user.schoolId

  const ilp = await prisma.individualLearningPlan.findFirst({
    where: { id: ilpId, schoolId },
    select: { id: true, studentId: true, sendCategory: true },
  })
  if (!ilp) throw new Error('ILP not found')

  // Archive any other active ILPs for this student first
  await prisma.individualLearningPlan.updateMany({
    where: { schoolId, studentId: ilp.studentId, id: { not: ilpId }, status: 'active' },
    data:  { status: 'archived' },
  })

  await prisma.individualLearningPlan.update({
    where: { id: ilpId },
    data: {
      status:          'active',
      approvedBySenco: true,
      approvedAt:      new Date(),
      approvedBy:      user.id,
    },
  })

  // Notify class teachers and HoY that an ILP is now active
  const [classTeachers, hoys, student] = await Promise.all([
    prisma.classTeacher.findMany({
      where: { class: { enrolments: { some: { userId: ilp.studentId } }, schoolId } },
      select: { userId: true },
    }),
    prisma.user.findMany({
      where: { schoolId, role: 'HEAD_OF_YEAR', isActive: true },
      select: { id: true },
    }),
    prisma.user.findUnique({
      where:  { id: ilp.studentId },
      select: { firstName: true, lastName: true },
    }),
  ])
  const studentName  = student ? `${student.firstName} ${student.lastName}` : 'a student'
  const notifyIds = [...new Set([...classTeachers.map(t => t.userId), ...hoys.map(h => h.id)])]

  if (notifyIds.length > 0) {
    await prisma.sendNotification.createMany({
      data: notifyIds.map(recipientId => ({
        schoolId,
        recipientId,
        type:  'ilp_created',
        title: `ILP approved: ${studentName}`,
        body:  `The Individual Learning Plan for ${studentName} (${ilp.sendCategory}) has been approved by the SENCO. Please review SEND strategies in your lesson planning.`,
      })),
    })
  }

  revalidatePath('/senco/ilp')

  // Auto-generate APDR from approved ILP
  void generateAPDRInternal(ilp.studentId, user.id, schoolId).catch(err =>
    console.error('[approveGeneratedIlp] generateAPDRInternal failed:', err)
  )

  // Auto-generate K Plan from approved ILP
  void generateLearnerPassportInternal(ilp.studentId, user.id, schoolId).catch(err =>
    console.error('[approveGeneratedIlp] generateLearnerPassportInternal failed:', err)
  )
}

// ─── APDR — Assess, Plan, Do, Review ─────────────────────────────────────────

const APDR_FIELD_LABELS: Record<string, string> = {
  assessContent:  'Assess',
  planContent:    'Plan',
  doContent:      'Do',
  reviewContent:  'Review',
}

/** Internal helper — creates an APDR cycle from existing ILP/EHCP data. No auth check. */
async function generateAPDRInternal(
  studentId: string,
  createdByUserId: string,
  schoolId: string,
): Promise<void> {
  // Skip if an ACTIVE APDR already exists
  const existing = await prisma.assessPlanDoReview.findFirst({
    where: { studentId, schoolId, status: 'ACTIVE' },
    select: { id: true },
  })
  if (existing) return

  const lastCompleted = await prisma.assessPlanDoReview.findFirst({
    where: { studentId, schoolId },
    orderBy: { cycleNumber: 'desc' },
    select: { cycleNumber: true },
  })
  const nextCycle = (lastCompleted?.cycleNumber ?? 0) + 1

  const [student, ilp, ehcp] = await Promise.all([
    prisma.user.findUnique({
      where: { id: studentId },
      select: { firstName: true, lastName: true, yearGroup: true, sendStatus: { select: { needArea: true } } },
    }),
    prisma.individualLearningPlan.findFirst({
      where: { schoolId, studentId, approvedBySenco: true, status: 'active' },
      include: { targets: { where: { status: 'active' }, take: 3 } },
      orderBy: { createdAt: 'desc' },
    }),
    prisma.ehcpPlan.findFirst({
      where: { schoolId, studentId, status: 'active' },
      select: { sections: true },
    }),
  ])
  if (!student) return

  let assessContent = ''
  let planContent   = ''

  const apiKey = process.env.ANTHROPIC_API_KEY
  if (apiKey && ilp) {
    try {
      const targetLines = ilp.targets.map((t, i) =>
        `  ${i + 1}. ${t.target} — strategy: ${t.strategy} — success: ${t.successMeasure}`
      ).join('\n')
      const ehcpSections = ehcp?.sections as Record<string, string> | null
      const ehcpCtx = ehcpSections
        ? `\nEHCP Section B: ${ehcpSections.B ?? ''}\nEHCP Section F: ${ehcpSections.F ?? ''}`
        : ''

      const { default: Anthropic } = await import('@anthropic-ai/sdk')
      const client = new Anthropic({ apiKey })
      const msg = await client.messages.create({
        model: 'claude-haiku-4-5-20251001', max_tokens: 600,
        system: 'You are a UK SENCO writing APDR cycle records. Return ONLY valid JSON, no markdown.',
        messages: [{
          role: 'user',
          content: `Generate Assess and Plan sections for an APDR cycle.

Student: ${student.firstName} ${student.lastName}, Year ${student.yearGroup ?? 9}
SEND category: ${student.sendStatus?.needArea ?? ilp.sendCategory}
ILP Strengths: ${ilp.currentStrengths}
ILP Areas of need: ${ilp.areasOfNeed}
ILP Strategies: ${ilp.strategies.join('; ')}${ehcpCtx}
Active targets:
${targetLines}

Return ONLY JSON:
{
  "assessContent": "3-4 sentences: strengths observed in class, areas requiring support, learner's voice and aspirations, key assessment findings",
  "planContent": "3-4 sentences: specific learning objectives this cycle, teaching strategies, TA support arrangements, how progress will be monitored"
}`,
        }],
      })
      const raw = (msg.content[0] as { type: string; text: string }).text.trim()
      const match = raw.match(/\{[\s\S]*\}/)
      if (match) {
        const gen = JSON.parse(match[0])
        assessContent = String(gen.assessContent ?? '')
        planContent   = String(gen.planContent   ?? '')
      }
    } catch (err) {
      console.error('[generateAPDRInternal] Claude call failed:', err)
    }
  }

  if (!assessContent && ilp) assessContent = `Strengths: ${ilp.currentStrengths}. Areas of need: ${ilp.areasOfNeed}`
  if (!planContent   && ilp) planContent   = `Strategies: ${ilp.strategies.join('; ')}. Success criteria: ${ilp.successCriteria}`

  await prisma.assessPlanDoReview.create({
    data: {
      schoolId, studentId, cycleNumber: nextCycle,
      assessContent:   assessContent || 'To be completed by SENCO.',
      planContent:     planContent   || 'To be completed by SENCO.',
      doContent:       '',
      reviewContent:   '',
      status:          'ACTIVE',
      reviewDate:      new Date(Date.now() + 13 * 7 * 24 * 60 * 60 * 1000),
      createdBy:       createdByUserId,
      approvedBySenco: false,
    },
  })
}

/** Generate (or regenerate) an APDR for a student — SENCO-callable server action. */
export async function generateAPDRForStudent(
  studentId: string,
): Promise<{ success: boolean; error?: string }> {
  try {
    const user = await requireSenco()
    await generateAPDRInternal(studentId, user.id, user.schoolId)
    revalidatePath(`/student/${studentId}/send`)
    return { success: true }
  } catch (err) {
    return { success: false, error: String(err).slice(0, 200) }
  }
}

/** Approve the current APDR — makes content visible to all staff. */
export async function approveAPDR(apdrId: string): Promise<void> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  const apdr = await prisma.assessPlanDoReview.findFirst({
    where: { id: apdrId, schoolId },
    select: { id: true, studentId: true },
  })
  if (!apdr) throw new Error('APDR not found')

  await prisma.assessPlanDoReview.update({
    where: { id: apdrId },
    data:  { approvedBySenco: true, approvedAt: new Date(), approvedBy: user.id },
  })

  revalidatePath(`/student/${apdr.studentId}/send`)
}

/** Update a single APDR section (with audit after approval). */
export async function updateAPDRSection(
  apdrId: string,
  section: 'assessContent' | 'planContent' | 'doContent' | 'reviewContent',
  newContent: string,
): Promise<void> {
  const user = await requireAuth()
  const allowedRoles = ['SENCO', 'TEACHER', 'HEAD_OF_DEPT', 'HEAD_OF_YEAR', 'SLT', 'SCHOOL_ADMIN']
  if (!allowedRoles.includes(user.role)) redirect('/dashboard')

  // Only SENCO-tier can edit Assess / Plan / Review; all staff can add Do notes
  const sencoOnly = ['assessContent', 'planContent', 'reviewContent']
  if (sencoOnly.includes(section) && !['SENCO', 'SLT', 'SCHOOL_ADMIN'].includes(user.role)) {
    throw new Error('Only SENCO can edit Assess, Plan and Review sections')
  }

  const apdr = await prisma.assessPlanDoReview.findFirst({
    where:  { id: apdrId, schoolId: user.schoolId },
    select: { assessContent: true, planContent: true, doContent: true, reviewContent: true, approvedBySenco: true, studentId: true },
  })
  if (!apdr) throw new Error('APDR not found')

  const previousValue = String(apdr[section] ?? '')

  await prisma.assessPlanDoReview.update({
    where: { id: apdrId },
    data:  { [section]: newContent },
  })

  if (apdr.approvedBySenco && previousValue !== newContent) {
    await writeAPDRAudit({
      apdrId,
      userId:        user.id,
      userName:      `${user.firstName} ${user.lastName}`,
      userRole:      user.role,
      fieldChanged:  APDR_FIELD_LABELS[section] ?? section,
      previousValue,
      newValue:      newContent,
      changeType:    !previousValue && newContent ? 'ADDED' : !newContent ? 'DELETED' : 'EDITED',
    })
  }

  revalidatePath(`/student/${apdr.studentId}/send`)
}

/**
 * Complete the review for this cycle.
 * Saves review text, marks COMPLETED, auto-starts next cycle.
 */
export async function completeAPDRReview(
  apdrId: string,
  reviewContent: string,
): Promise<void> {
  const user = await requireSenco()
  const schoolId = user.schoolId

  const apdr = await prisma.assessPlanDoReview.findFirst({
    where:  { id: apdrId, schoolId },
    select: { id: true, studentId: true, approvedBySenco: true, reviewContent: true },
  })
  if (!apdr) throw new Error('APDR not found')

  await prisma.assessPlanDoReview.update({
    where: { id: apdrId },
    data:  { status: 'COMPLETED', reviewContent },
  })

  if (apdr.approvedBySenco && (apdr.reviewContent ?? '') !== reviewContent) {
    await writeAPDRAudit({
      apdrId,
      userId:        user.id,
      userName:      `${user.firstName} ${user.lastName}`,
      userRole:      user.role,
      fieldChanged:  'Review',
      previousValue: apdr.reviewContent ?? '',
      newValue:      reviewContent,
      changeType:    !apdr.reviewContent && reviewContent ? 'ADDED' : 'EDITED',
    })
  }

  void generateAPDRInternal(apdr.studentId, user.id, schoolId).catch(err =>
    console.error('[completeAPDRReview] generateAPDRInternal failed:', err)
  )

  // Auto-regenerate K Plan when a review cycle completes
  void generateLearnerPassportInternal(apdr.studentId, user.id, schoolId).catch(err =>
    console.error('[completeAPDRReview] generateLearnerPassportInternal failed:', err)
  )

  revalidatePath(`/student/${apdr.studentId}/send`)
}

/** Fetch all APDR cycles for a student — newest first. */
export async function getStudentAPDRCycles(studentId: string): Promise<ApdrRow[]> {
  const user = await requireAuth()
  const allowedRoles = ['SENCO', 'TEACHER', 'HEAD_OF_DEPT', 'HEAD_OF_YEAR', 'SLT', 'SCHOOL_ADMIN']
  if (!allowedRoles.includes(user.role)) return []

  const cycles = await prisma.assessPlanDoReview.findMany({
    where:   { studentId, schoolId: user.schoolId },
    orderBy: { cycleNumber: 'desc' },
  })

  return cycles.map(c => ({
    id: c.id, studentId: c.studentId, schoolId: c.schoolId,
    cycleNumber: c.cycleNumber, assessContent: c.assessContent,
    planContent: c.planContent, doContent: c.doContent, reviewContent: c.reviewContent,
    status: c.status, reviewDate: c.reviewDate, createdBy: c.createdBy,
    approvedBySenco: c.approvedBySenco, approvedAt: c.approvedAt,
    approvedBy: c.approvedBy, createdAt: c.createdAt, updatedAt: c.updatedAt,
  }))
}

/** Audit log for an APDR — SENCO/SLT/SCHOOL_ADMIN see all; others see own only. */
export async function getAPDRAuditLog(apdrId: string): Promise<ApdrAuditEntryRow[]> {
  const user = await requireAuth()
  const allowedRoles = ['SENCO', 'TEACHER', 'HEAD_OF_DEPT', 'HEAD_OF_YEAR', 'SLT', 'SCHOOL_ADMIN']
  if (!allowedRoles.includes(user.role)) return []

  const fullAccess = ['SENCO', 'SLT', 'SCHOOL_ADMIN'].includes(user.role)
  const entries = await prisma.apdrAuditEntry.findMany({
    where: { apdrId, ...(fullAccess ? {} : { userId: user.id }) },
    orderBy: { createdAt: 'desc' },
  })

  return entries.map(e => ({
    id: e.id, apdrId: e.apdrId, userId: e.userId,
    userName: e.userName, userRole: e.userRole, fieldChanged: e.fieldChanged,
    previousValue: e.previousValue, newValue: e.newValue,
    changeType: e.changeType, createdAt: e.createdAt,
  }))
}

/** Returns the current user's role — used by client components. */
export async function getCurrentUserRole(): Promise<string | null> {
  const session = await auth()
  return (session?.user as any)?.role ?? null
}

// ─── K Plan (Learning Passport) ───────────────────────────────────────────────

function buildKPlanPrompt(
  firstName: string,
  lastName: string,
  yearGroup: number,
  needArea: string,
  ilp: {
    currentStrengths: string
    areasOfNeed: string
    strategies: string[]
    targets: { target: string; strategy: string }[]
  } | null,
  ehcpSections: { B?: string; F?: string } | null,
  apdr: { assessContent: string; planContent: string; doContent: string } | null,
): string {
  const sections: string[] = []
  if (ilp) {
    sections.push(`ILP Strengths: ${ilp.currentStrengths}`)
    sections.push(`ILP Areas of need: ${ilp.areasOfNeed}`)
    sections.push(`ILP Strategies: ${ilp.strategies.join('; ')}`)
    if (ilp.targets.length > 0) {
      sections.push('ILP Targets: ' + ilp.targets.map(t => `${t.target} (${t.strategy})`).join('; '))
    }
  }
  if (ehcpSections?.B) sections.push(`EHCP needs (Section B): ${ehcpSections.B}`)
  if (ehcpSections?.F) sections.push(`EHCP provision (Section F): ${ehcpSections.F}`)
  if (apdr?.assessContent) sections.push(`APDR Assess: ${apdr.assessContent}`)
  if (apdr?.planContent)   sections.push(`APDR Plan: ${apdr.planContent}`)
  if (apdr?.doContent)     sections.push(`APDR Do (what's working): ${apdr.doContent}`)

  return `Create a K Plan (Learning Passport) for a UK secondary school student.

Student: ${firstName} ${lastName}, Year ${yearGroup}
SEND category: ${needArea}
${sections.join('\n')}

Return ONLY valid JSON:
{
  "sendInformation": "3–4 sentences describing ${firstName}'s SEND context, key diagnosis or category, characteristic classroom behaviours and learning profile — factual and professional",
  "teacherActions": [
    "Seat ${firstName} at the front of the class, away from windows and doors",
    "Give ${firstName} a printed or digital copy of all handouts before the lesson begins",
    "Break all verbal instructions into 2–3 steps maximum — check ${firstName} has understood before moving on",
    "Allow ${firstName} extra processing time on written tasks",
    "Check in with ${firstName} after each task — brief, private check rather than whole-class",
    "Provide a visual timer when ${firstName} is working independently",
    "Allow ${firstName} to use assistive technology or overlays as needed"
  ],
  "studentCommitments": [
    "I will ask for help when I am stuck rather than guessing or giving up",
    "I will bring my planner and all equipment to every lesson",
    "I will use my reading overlay for written tasks",
    "I will tell my teacher if I do not understand the instructions"
  ]
}

teacherActions: 6–8 items. Each must be specific, actionable, and use ${firstName}'s name. Not generic advice — concrete classroom instructions.
studentCommitments: 4–6 items written in first person ("I will..."). Written as if spoken by the student.`
}

/**
 * Internal helper — generates or regenerates a LearnerPassport (K Plan) from
 * the student's latest ILP, EHCP and APDR cycle. No auth — called by triggers.
 */
export async function generateLearnerPassportInternal(
  studentId: string,
  createdByUserId: string,
  schoolId: string,
): Promise<void> {
  const [student, ilp, ehcp, apdr] = await Promise.all([
    prisma.user.findUnique({
      where: { id: studentId },
      select: { firstName: true, lastName: true, yearGroup: true, sendStatus: { select: { needArea: true } } },
    }),
    prisma.individualLearningPlan.findFirst({
      where: { schoolId, studentId, status: 'active', approvedBySenco: true },
      include: { targets: { where: { status: 'active' }, take: 3 } },
      orderBy: { createdAt: 'desc' },
    }),
    prisma.ehcpPlan.findFirst({
      where: { schoolId, studentId, status: 'active' },
      select: { id: true, sections: true },
    }),
    prisma.assessPlanDoReview.findFirst({
      where: { schoolId, studentId },
      orderBy: { cycleNumber: 'desc' },
      select: { id: true, assessContent: true, planContent: true, doContent: true },
    }),
  ])
  if (!student) return

  const needArea  = student.sendStatus?.needArea ?? 'General Learning Support'
  const yearGroup = student.yearGroup ?? 9

  let sendInformation    = ''
  let teacherActions:     string[] = []
  let studentCommitments: string[] = []

  const apiKey = process.env.ANTHROPIC_API_KEY
  if (apiKey) {
    try {
      const { default: Anthropic } = await import('@anthropic-ai/sdk')
      const client = new Anthropic({ apiKey })
      const ehcpSecs = ehcp?.sections as Record<string, string> | null

      const msg = await client.messages.create({
        model: 'claude-sonnet-4-6', max_tokens: 800,
        system: 'You are a UK SENCO writing a Learning Passport (K Plan). Return ONLY valid JSON, no markdown.',
        messages: [{
          role: 'user',
          content: buildKPlanPrompt(
            student.firstName, student.lastName, yearGroup, needArea,
            ilp ? {
              currentStrengths: ilp.currentStrengths,
              areasOfNeed:      ilp.areasOfNeed,
              strategies:       ilp.strategies,
              targets:          ilp.targets.map(t => ({ target: t.target, strategy: t.strategy })),
            } : null,
            ehcpSecs ? { B: ehcpSecs.B, F: ehcpSecs.F } : null,
            apdr ?? null,
          ),
        }],
      })

      const raw   = (msg.content[0] as { type: string; text: string }).text.trim()
      const match = raw.match(/\{[\s\S]*\}/)
      if (match) {
        const gen = JSON.parse(match[0])
        sendInformation    = String(gen.sendInformation ?? '')
        teacherActions     = Array.isArray(gen.teacherActions)     ? gen.teacherActions.map(String)     : []
        studentCommitments = Array.isArray(gen.studentCommitments) ? gen.studentCommitments.map(String) : []
      }
    } catch (err) {
      console.error('[generateLearnerPassportInternal] Claude call failed:', err)
    }
  }

  // Fallback if AI failed
  if (!sendInformation && ilp) {
    sendInformation = `${student.firstName} ${student.lastName} is a Year ${yearGroup} student with ${needArea}. ${ilp.currentStrengths}. Areas of need: ${ilp.areasOfNeed}.`
  }
  if (teacherActions.length === 0 && ilp) {
    teacherActions = ilp.strategies.slice(0, 6)
  }
  if (studentCommitments.length === 0) {
    studentCommitments = [
      'I will ask for help when I am stuck',
      'I will bring all equipment to every lesson',
      'I will let my teacher know if I do not understand',
    ]
  }

  // Upsert — one LearnerPassport per student (overwrite existing DRAFT, never overwrite APPROVED)
  const existing = await prisma.learnerPassport.findFirst({
    where: { studentId, schoolId },
    orderBy: { createdAt: 'desc' },
    select: { id: true, status: true },
  })

  if (existing && existing.status === 'APPROVED') {
    // Create a new DRAFT alongside the approved one
    await prisma.learnerPassport.create({
      data: {
        schoolId, studentId,
        ilpId:  ilp?.id ?? null,
        ehcpId: ehcp?.id ?? null,
        apdrId: apdr?.id ?? null,
        sendInformation, teacherActions, studentCommitments,
        status: 'DRAFT',
        generatedAt: new Date(),
      },
    })
  } else if (existing && existing.status === 'DRAFT') {
    // Overwrite the existing DRAFT
    await prisma.learnerPassport.update({
      where: { id: existing.id },
      data: {
        ilpId:  ilp?.id ?? null,
        ehcpId: ehcp?.id ?? null,
        apdrId: apdr?.id ?? null,
        sendInformation, teacherActions, studentCommitments,
        generatedAt: new Date(),
      },
    })
  } else {
    await prisma.learnerPassport.create({
      data: {
        schoolId, studentId,
        ilpId:  ilp?.id ?? null,
        ehcpId: ehcp?.id ?? null,
        apdrId: apdr?.id ?? null,
        sendInformation, teacherActions, studentCommitments,
        status: 'DRAFT',
        generatedAt: new Date(),
      },
    })
  }
}

/** Generate (or regenerate) a Learning Passport for a student — SENCO callable. */
export async function generateLearnerPassport(
  studentId: string,
): Promise<{ success: boolean; error?: string }> {
  try {
    const user = await requireSenco()
    await generateLearnerPassportInternal(studentId, user.id, user.schoolId)
    revalidatePath(`/student/${studentId}/send`)
    return { success: true }
  } catch (err) {
    return { success: false, error: String(err).slice(0, 200) }
  }
}

/** Regenerate — force-overwrites even an APPROVED plan (creates new DRAFT). SENCO only. */
export async function regenerateLearnerPassport(
  studentId: string,
): Promise<{ success: boolean; error?: string }> {
  try {
    const user = await requireSenco()
    // Delete existing DRAFT to force a fresh create
    await prisma.learnerPassport.deleteMany({
      where: { studentId, schoolId: user.schoolId, status: 'DRAFT' },
    })
    await generateLearnerPassportInternal(studentId, user.id, user.schoolId)
    revalidatePath(`/student/${studentId}/send`)
    return { success: true }
  } catch (err) {
    return { success: false, error: String(err).slice(0, 200) }
  }
}

/** Approve a Learning Passport — makes it visible to all teachers. SENCO only. */
export async function approveLearnerPassport(passportId: string): Promise<void> {
  const user = await requireSenco()

  const passport = await prisma.learnerPassport.findFirst({
    where: { id: passportId, schoolId: user.schoolId },
    select: { studentId: true },
  })
  if (!passport) throw new Error('Learning Passport not found')

  // Mark previous approved plans as superseded (set them to DRAFT so only one is APPROVED)
  await prisma.learnerPassport.updateMany({
    where: { studentId: passport.studentId, schoolId: user.schoolId, status: 'APPROVED' },
    data:  { status: 'DRAFT' },
  })

  await prisma.learnerPassport.update({
    where: { id: passportId },
    data:  { status: 'APPROVED', approvedBy: user.id, approvedAt: new Date() },
  })

  revalidatePath(`/student/${passport.studentId}/send`)
}

/** Fetch the latest Learning Passport for a student. All staff can view. */
export async function getStudentLearnerPassport(studentId: string): Promise<LearnerPassportRow | null> {
  const user = await requireAuth()
  const allowedRoles = ['SENCO', 'TEACHER', 'HEAD_OF_DEPT', 'HEAD_OF_YEAR', 'SLT', 'SCHOOL_ADMIN']
  if (!allowedRoles.includes(user.role)) return null

  // SENCO sees latest (including DRAFT); teachers see APPROVED only
  const isSencoTier = ['SENCO', 'SLT', 'SCHOOL_ADMIN'].includes(user.role)

  const passport = await prisma.learnerPassport.findFirst({
    where: {
      studentId,
      schoolId: user.schoolId,
      ...(isSencoTier ? {} : { status: 'APPROVED' }),
    },
    orderBy: [
      { status: 'asc' },   // APPROVED < DRAFT alphabetically → shows APPROVED first
      { createdAt: 'desc' },
    ],
  })
  if (!passport) return null

  return {
    id:                 passport.id,
    studentId:          passport.studentId,
    schoolId:           passport.schoolId,
    ilpId:              passport.ilpId,
    ehcpId:             passport.ehcpId,
    apdrId:             passport.apdrId,
    sendInformation:    passport.sendInformation,
    teacherActions:     passport.teacherActions,
    studentCommitments: passport.studentCommitments,
    status:             passport.status,
    approvedBy:         passport.approvedBy,
    approvedAt:         passport.approvedAt,
    generatedAt:        passport.generatedAt,
    createdAt:          passport.createdAt,
    updatedAt:          passport.updatedAt,
  }
}

/**
 * Batch-fetch K Plan status for all students in a class.
 * Returns a map of studentId → { id, sendInformation, status }.
 * Teachers only see APPROVED plans; SENCO sees all.
 */
export async function getClassKPlanSummaries(
  classId: string,
): Promise<Record<string, { id: string; sendInformation: string; status: string }>> {
  const user = await requireAuth()
  const allowedRoles = ['SENCO', 'TEACHER', 'HEAD_OF_DEPT', 'HEAD_OF_YEAR', 'SLT', 'SCHOOL_ADMIN']
  if (!allowedRoles.includes(user.role)) return {}

  const isSencoTier = ['SENCO', 'SLT', 'SCHOOL_ADMIN'].includes(user.role)

  const enrolments = await prisma.enrolment.findMany({
    where: { classId, class: { schoolId: user.schoolId } },
    select: { userId: true },
  })
  const studentIds = enrolments.map(e => e.userId)
  if (studentIds.length === 0) return {}

  const passports = await prisma.learnerPassport.findMany({
    where: {
      studentId: { in: studentIds },
      schoolId:  user.schoolId,
      ...(isSencoTier ? {} : { status: 'APPROVED' }),
    },
    orderBy: { createdAt: 'desc' },
    select: { id: true, studentId: true, sendInformation: true, status: true },
  })

  // Keep only the latest per student
  const result: Record<string, { id: string; sendInformation: string; status: string }> = {}
  for (const p of passports) {
    if (!result[p.studentId]) {
      result[p.studentId] = { id: p.id, sendInformation: p.sendInformation, status: p.status }
    }
  }
  return result
}
