import { pdfShell, escHtml } from './templates'

export type EhcpReviewPdfData = {
  studentName:      string
  yearGroup:        number | null
  localAuthority:   string
  schoolName:       string
  reviewDate:       Date
  reviewerName:     string
  summary:          string
  progressRating:   string
  parentComments:   string
  amendmentsNeeded: boolean
  newReviewDate:    Date
  laNotified:       boolean
}

const PROGRESS_LABELS: Record<string, string> = {
  GOOD_PROGRESS: 'Making Good Progress',
  SOME_PROGRESS: 'Making Some Progress',
  INSUFFICIENT:  'Insufficient Progress',
  NO_PROGRESS:   'No Progress Made',
}

const PROGRESS_COLORS: Record<string, string> = {
  GOOD_PROGRESS: 'card-green',
  SOME_PROGRESS: 'card-blue',
  INSUFFICIENT:  'card-amber',
  NO_PROGRESS:   'card-red',
}

export function ehcpReviewPdf(data: EhcpReviewPdfData): string {
  const fmtDate = (d: Date) =>
    new Date(d).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
  const now = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

  const progressLabel = PROGRESS_LABELS[data.progressRating] ?? data.progressRating
  const progressColor = PROGRESS_COLORS[data.progressRating] ?? 'card'

  const summaryParagraphs = data.summary
    .split('\n')
    .filter(l => l.trim())
    .map(l => `<p>${escHtml(l)}</p>`)
    .join('')

  const parentParagraphs = data.parentComments
    ? data.parentComments.split('\n').filter(l => l.trim()).map(l => `<p>${escHtml(l)}</p>`).join('')
    : ''

  const body = `
    <h1>EHCP Annual Review — ${escHtml(data.studentName)}</h1>
    <p style="color:#6b7280; font-size:10pt; margin-bottom:6pt;">
      Education, Health and Care Plan — Statutory Annual Review Record
    </p>

    <table style="margin-bottom:16pt; font-size:10pt;">
      <tr>
        <td style="width:30%; color:#6b7280; font-weight:600;">Student</td>
        <td>${escHtml(data.studentName)}${data.yearGroup ? ` · Year ${data.yearGroup}` : ''}</td>
      </tr>
      <tr>
        <td style="color:#6b7280; font-weight:600;">School</td>
        <td>${escHtml(data.schoolName)}</td>
      </tr>
      <tr>
        <td style="color:#6b7280; font-weight:600;">Local Authority</td>
        <td>${escHtml(data.localAuthority)}</td>
      </tr>
      <tr>
        <td style="color:#6b7280; font-weight:600;">Review date</td>
        <td>${fmtDate(data.reviewDate)}</td>
      </tr>
      <tr>
        <td style="color:#6b7280; font-weight:600;">Reviewed by</td>
        <td>${escHtml(data.reviewerName)}</td>
      </tr>
      <tr>
        <td style="color:#6b7280; font-weight:600;">Next review date</td>
        <td>${fmtDate(data.newReviewDate)}</td>
      </tr>
      <tr>
        <td style="color:#6b7280; font-weight:600;">LA notified</td>
        <td>${data.laNotified ? '✓ Yes' : 'Not yet'}</td>
      </tr>
    </table>

    ${data.progressRating ? `
    <h2>Overall Progress Rating</h2>
    <div class="${progressColor}" style="margin-bottom:14pt;">
      <p style="font-size:13pt; font-weight:700; margin-bottom:0;">${escHtml(progressLabel)}</p>
    </div>` : ''}

    <h2>Review Summary</h2>
    <div class="card">${summaryParagraphs}</div>

    ${parentParagraphs ? `
    <h2>Parent / Carer Comments</h2>
    <div class="card">${parentParagraphs}</div>` : ''}

    ${data.amendmentsNeeded ? `
    <h2>Amendments</h2>
    <div class="card-amber">
      <p>⚠ Amendments to the EHCP have been recommended following this review. The Local Authority should be notified to initiate the amendment process.</p>
    </div>` : ''}

    <p style="margin-top:24pt; font-size:9pt; color:#9ca3af; border-top:0.5pt solid #e5e7eb; padding-top:6pt;">
      Generated by Omnis · ${now} · EHCP data is Special Category under UK GDPR Article 9 — handle in accordance with your school's data protection policy.
    </p>
  `

  return pdfShell(body, `EHCP Annual Review — ${data.studentName}`, data.schoolName)
}
