/*
 * DEPLOYMENT NOTE:
 * This uses puppeteer (full) which bundles Chromium — fine for development.
 * For Vercel serverless deployment, swap to:
 *   npm install puppeteer-core @sparticuz/chromium
 * And update generator.ts to use:
 *   import chromium from '@sparticuz/chromium'
 *   import puppeteer from 'puppeteer-core'
 *   const browser = await puppeteer.launch({
 *     args: chromium.args,
 *     executablePath: await chromium.executablePath(),
 *     headless: chromium.headless,
 *   })
 * Also set: export const maxDuration = 60 on each export route.
 */

import puppeteer from 'puppeteer'

export type PdfOptions = {
  format?:    'A4' | 'Letter'
  landscape?: boolean
  margin?:    { top?: string; right?: string; bottom?: string; left?: string }
}

const DEFAULT_OPTIONS: PdfOptions = {
  format:    'A4',
  landscape: false,
  margin:    { top: '15mm', right: '15mm', bottom: '20mm', left: '15mm' },
}

export async function generatePdf(html: string, options: PdfOptions = {}): Promise<ArrayBuffer> {
  const opts = { ...DEFAULT_OPTIONS, ...options }

  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  })

  try {
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'networkidle0' })

    const pdfBuf = await page.pdf({
      format:           opts.format as 'A4' | 'Letter',
      landscape:        opts.landscape,
      margin:           opts.margin,
      printBackground:  true,
      displayHeaderFooter: true,
      headerTemplate:   '<span></span>',
      footerTemplate:   `
        <div style="font-size:9px;color:#999;width:100%;text-align:center;padding:0 15mm;box-sizing:border-box;">
          <span class="pageNumber"></span> / <span class="totalPages"></span>
          &nbsp;·&nbsp; Generated by Omnis
        </div>`,
    })

    // Copy into a fresh ArrayBuffer (satisfies strict BodyInit typing)
    const copy = new ArrayBuffer(pdfBuf.byteLength)
    new Uint8Array(copy).set(new Uint8Array(pdfBuf.buffer, pdfBuf.byteOffset, pdfBuf.byteLength))
    return copy
  } finally {
    await browser.close()
  }
}
