/**
 * PDF generation using Puppeteer.
 *
 * On Vercel/Lambda (process.env.VERCEL is set), uses @sparticuz/chromium +
 * puppeteer-core for a self-contained Chromium binary compatible with the
 * serverless environment.
 *
 * Locally, falls back to the full puppeteer package which manages its own
 * Chrome download.
 */

import puppeteerCore from 'puppeteer-core'
import type { Browser } from 'puppeteer-core'

async function launchBrowser(): Promise<Browser> {
  if (process.env.VERCEL || process.env.AWS_LAMBDA_FUNCTION_NAME) {
    const chromium = (await import('@sparticuz/chromium')).default
    // ETXTBSY can occur on cold-start when two Lambda invocations try to extract
    // the Chromium binary simultaneously. Retry up to 2 times with back-off.
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        return await puppeteerCore.launch({
          args:           [...chromium.args, '--no-sandbox', '--disable-setuid-sandbox'],
          executablePath: await chromium.executablePath(),
          headless:       true,
        }) as unknown as Browser
      } catch (err) {
        const code = (err as NodeJS.ErrnoException).code
        if (code === 'ETXTBSY' && attempt < 2) {
          await new Promise(r => setTimeout(r, 500 * (attempt + 1)))
          continue
        }
        throw err
      }
    }
    throw new Error('Failed to launch browser after 3 attempts')
  }
  // Docker/container: use system Chromium pointed to by PUPPETEER_EXECUTABLE_PATH
  // (set in Dockerfile via `apk add chromium` + ENV PUPPETEER_EXECUTABLE_PATH)
  const executablePath = process.env.PUPPETEER_EXECUTABLE_PATH
  if (executablePath) {
    return await puppeteerCore.launch({
      executablePath,
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu'],
    }) as unknown as Browser
  }
  // Local dev: use full puppeteer's managed Chrome
  const puppeteer = (await import('puppeteer')).default
  return puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  }) as unknown as Browser
}

export type PdfOptions = {
  format?:    'A4' | 'Letter'
  landscape?: boolean
  margin?:    { top?: string; right?: string; bottom?: string; left?: string }
}

const DEFAULT_OPTIONS: PdfOptions = {
  format:    'A4',
  landscape: false,
  margin:    { top: '15mm', right: '15mm', bottom: '20mm', left: '15mm' },
}

export async function generatePdf(html: string, options: PdfOptions = {}): Promise<ArrayBuffer> {
  const opts = { ...DEFAULT_OPTIONS, ...options }

  const browser = await launchBrowser()

  try {
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'load' })

    const pdfBuf = await page.pdf({
      format:           opts.format as 'A4' | 'Letter',
      landscape:        opts.landscape,
      margin:           opts.margin,
      printBackground:  true,
      displayHeaderFooter: true,
      headerTemplate:   '<span></span>',
      footerTemplate:   `
        <div style="font-size:9px;color:#999;width:100%;text-align:center;padding:0 15mm;box-sizing:border-box;">
          <span class="pageNumber"></span> / <span class="totalPages"></span>
          &nbsp;·&nbsp; Generated by Omnis
        </div>`,
    })

    // Copy into a fresh ArrayBuffer (satisfies strict BodyInit typing)
    const copy = new ArrayBuffer(pdfBuf.byteLength)
    new Uint8Array(copy).set(new Uint8Array(pdfBuf.buffer, pdfBuf.byteOffset, pdfBuf.byteLength))
    return copy
  } finally {
    await browser.close()
  }
}
