import { pdfShell, escHtml } from './templates'

export type ParentContactLogPdfData = {
  studentName:  string
  yearGroup:    number | null
  formClass:    string | null
  schoolName:   string
  entries: {
    contactDate: string   // ISO
    method:      string
    summary:     string
    outcome:     string | null
    authorName:  string
    authorRole:  string
  }[]
}

const METHOD_LABELS: Record<string, string> = {
  PHONE:   'Phone call',
  EMAIL:   'Email',
  MEETING: 'Meeting',
  LETTER:  'Letter',
  OTHER:   'Other',
}

export function parentContactLogPdf(data: ParentContactLogPdfData): string {
  const fmtDate = (iso: string) =>
    new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

  const rows = data.entries.length === 0
    ? '<tr><td colspan="4" style="text-align:center;color:#6b7280;padding:12pt;">No contact entries recorded.</td></tr>'
    : data.entries.map(e => `
        <tr>
          <td style="white-space:nowrap;">${escHtml(fmtDate(e.contactDate))}</td>
          <td>${escHtml(METHOD_LABELS[e.method] ?? e.method)}</td>
          <td>
            <p style="margin-bottom:3pt;">${escHtml(e.summary)}</p>
            ${e.outcome ? `<p class="text-muted text-sm">Outcome: ${escHtml(e.outcome)}</p>` : ''}
          </td>
          <td class="text-muted">${escHtml(e.authorName)}</td>
        </tr>
      `).join('')

  const body = `
    <div style="margin-bottom:16pt;">
      <h1>Parent Contact Log</h1>
      <p class="meta">
        ${escHtml(data.studentName)}
        ${data.yearGroup ? ` · Year ${data.yearGroup}` : ''}
        ${data.formClass ? ` · Form ${escHtml(data.formClass)}` : ''}
        &nbsp;·&nbsp; ${escHtml(data.schoolName)}
      </p>
      <p class="meta" style="margin-top:2pt;">${data.entries.length} entr${data.entries.length === 1 ? 'y' : 'ies'} recorded</p>
    </div>

    <table>
      <thead>
        <tr>
          <th style="width:110pt;">Date</th>
          <th style="width:80pt;">Method</th>
          <th>Notes</th>
          <th style="width:90pt;">Logged by</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
      </tbody>
    </table>

    <p class="meta" style="margin-top:12pt;font-style:italic;">
      This log is confidential and intended for school staff use only.
      Generated by Omnis on ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}.
    </p>
  `

  return pdfShell(body, `Parent Contact Log — ${data.studentName}`, data.schoolName)
}
