import { pdfShell } from './templates'
import type { SafeguardingLog, SafeguardingRow } from '@/app/actions/safeguarding'

const PRIORITY_COLOUR: Record<string, string> = {
  low:      '#6b7280',
  medium:   '#d97706',
  high:     '#ea580c',
  critical: '#dc2626',
}

const STATUS_COLOUR: Record<string, string> = {
  open:       '#2563eb',
  referred:   '#7c3aed',
  monitoring: '#d97706',
  closed:     '#16a34a',
}

function badge(label: string, colour: string) {
  return `<span style="display:inline-block;padding:1pt 6pt;border-radius:4pt;font-size:8pt;font-weight:600;color:#fff;background:${colour};margin-right:4pt;">${label.toUpperCase()}</span>`
}

function dateStr(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}

function renderRows(rows: SafeguardingRow[]): string {
  if (rows.length === 0) return '<p class="text-muted text-sm">No records in this category.</p>'
  return `
    <table>
      <thead>
        <tr>
          <th>Student</th>
          <th>Category</th>
          <th>Priority</th>
          <th>Logged by</th>
          <th>Date</th>
          <th>DSL</th>
        </tr>
      </thead>
      <tbody>
        ${rows.map(r => `
          <tr>
            <td>
              <strong>${r.studentName}</strong>
              ${r.yearGroup ? `<br><span class="text-muted">Year ${r.yearGroup}</span>` : ''}
            </td>
            <td>${r.category}</td>
            <td>${badge(r.priority, PRIORITY_COLOUR[r.priority] ?? '#6b7280')}</td>
            <td>${r.authorName}</td>
            <td>${dateStr(r.createdAt)}</td>
            <td>${r.referredToDSL ? '<span style="color:#16a34a;font-weight:600;">Yes</span>' : '<span class="text-muted">No</span>'}</td>
          </tr>
          ${r.description ? `
          <tr>
            <td colspan="6" style="padding-top:0;padding-bottom:8pt;background:#fafafa;">
              <span class="text-muted" style="font-size:8.5pt;">${r.description.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</span>
              ${r.dslNotes ? `<br><em style="font-size:8.5pt;color:#7c3aed;">DSL notes: ${r.dslNotes.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</em>` : ''}
            </td>
          </tr>` : ''}
        `).join('')}
      </tbody>
    </table>
  `
}

export function safeguardingLogPdf(log: SafeguardingLog, schoolName: string, generatedBy: string): string {
  const now = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

  const content = `
    <div class="card card-red" style="margin-bottom:14pt;">
      <strong style="color:#dc2626;">CONFIDENTIAL — RESTRICTED ACCESS</strong><br>
      <span class="text-sm">This document is for the Designated Safeguarding Lead and authorised staff only.
      It must be stored securely and not shared without DSL approval.</span>
    </div>

    <div class="two-col" style="margin-bottom:14pt;">
      <div>
        <p class="meta">School</p>
        <p><strong>${schoolName}</strong></p>
      </div>
      <div>
        <p class="meta">Generated by</p>
        <p><strong>${generatedBy}</strong></p>
        <p class="meta">${now}</p>
      </div>
    </div>

    <!-- KPI summary -->
    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10pt;margin-bottom:16pt;">
      ${[
        { label: 'Total records', value: log.stats.total, colour: '#374151' },
        { label: 'Open',          value: log.stats.open,     colour: '#2563eb' },
        { label: 'Referred',      value: log.stats.referred, colour: '#7c3aed' },
        { label: 'Critical',      value: log.stats.critical, colour: '#dc2626' },
      ].map(s => `
        <div style="border:1pt solid #e5e7eb;border-radius:6pt;padding:8pt 10pt;text-align:center;">
          <p style="font-size:18pt;font-weight:700;color:${s.colour};margin-bottom:2pt;">${s.value}</p>
          <p class="meta">${s.label}</p>
        </div>
      `).join('')}
    </div>

    <!-- Open records -->
    <h2 style="color:${STATUS_COLOUR.open};">Open (${log.open.length})</h2>
    ${renderRows(log.open)}

    <!-- Referred records -->
    <h2 style="color:${STATUS_COLOUR.referred};">Referred to External Agency (${log.referred.length})</h2>
    ${renderRows(log.referred)}

    <!-- Monitoring records -->
    <h2 style="color:${STATUS_COLOUR.monitoring};">Monitoring (${log.monitoring.length})</h2>
    ${renderRows(log.monitoring)}

    <!-- Closed records -->
    <h2 style="color:${STATUS_COLOUR.closed};">Closed (${log.closed.length})</h2>
    ${renderRows(log.closed)}

    <div class="divider"></div>
    <p class="text-muted text-sm" style="margin-top:8pt;">
      This report was generated from the Omnis safeguarding log on ${now} by ${generatedBy}.
      All information is subject to data protection legislation and school safeguarding policy.
    </p>
  `

  return pdfShell(content, 'Safeguarding Log', schoolName)
}
