'use client'

/**
 * components/students/AiDecisionExplanation.tsx
 *
 * Renders one AgentAuditEntry as a plain-language explanation, per the
 * template in dspy-service/XAI.md's "per-decision explanation" section:
 *
 *   This suggestion was generated by Omnis's [agent] on [date]. It used
 *   [standards] and was based on [inputs]. The system rated its own
 *   confidence at [X]%. It was reviewed by [reviewer] on [date], who
 *   [confirmed / edited / dismissed it]. [reviewNote, if left]
 *
 * Deliberately template-filled from the row's own fields, not LLM-generated —
 * see XAI.md's "what this deliberately does not claim". Used both inline
 * (wherever a suggestion is shown) and inside AiJourneyTab's timeline.
 */

import type { AiJourneyEntry } from '@/app/actions/agent-insights'

function formatDate(d: Date | string) {
  return new Date(d).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}

function describeInputRefs(refs: Record<string, unknown>): string | null {
  const keys = Object.keys(refs)
  if (!keys.length) return null
  // inputRefs holds whatever the agent was given at call time (lesson, student,
  // resource IDs, etc.) — show the field names rather than raw IDs, since IDs
  // alone mean nothing to a parent or inspector reading this.
  return keys.map(k => k.replace(/([A-Z])/g, ' $1').toLowerCase().trim()).join(', ')
}

export default function AiDecisionExplanation({
  entry,
  compact = false,
}: {
  entry: AiJourneyEntry
  compact?: boolean
}) {
  const inputDescription = describeInputRefs(entry.inputRefs)
  const outcomeText =
    entry.reviewOutcome === 'CONFIRMED'  ? 'confirmed it as-is' :
    entry.reviewOutcome === 'OVERRIDDEN' ? 'edited it before use' :
    entry.reviewOutcome === 'DISMISSED'  ? 'dismissed it — no action taken' :
    null

  return (
    <div className={compact ? 'text-sm' : 'text-sm bg-white rounded-lg border border-gray-200 p-4'}>
      <div className="flex items-center gap-2 mb-1.5 flex-wrap">
        <span className="inline-flex items-center px-2 py-0.5 rounded-full bg-blue-50 text-blue-700 text-xs font-medium">
          {entry.agentLabel}
        </span>
        <span className="inline-flex items-center px-2 py-0.5 rounded-full bg-gray-100 text-gray-600 text-xs font-medium">
          {entry.skillLabel}
        </span>
        <span className="text-xs text-gray-400">v{entry.skillVersion}</span>
        <span className="text-xs text-gray-400">{formatDate(entry.createdAt)}</span>
      </div>

      <p className="text-gray-800 leading-relaxed">
        This suggestion was generated by Omnis&rsquo;s <strong>{entry.agentLabel}</strong> agent on {formatDate(entry.createdAt)}.
        {entry.standardsApplied.length > 0 && (
          <> It applied {entry.standardsApplied.join(', ')}.</>
        )}
        {inputDescription && (
          <> It was based on this student&rsquo;s {inputDescription}.</>
        )}
        {' '}The system rated its own confidence at {entry.confidence}%.
      </p>

      <p className="text-gray-800 leading-relaxed mt-2">
        <strong>Output:</strong> {entry.outputSummary}
      </p>

      <p className="text-gray-600 mt-2">
        {outcomeText ? (
          <>
            Reviewed by <strong>{entry.reviewedByName ?? 'a member of staff'}</strong>
            {entry.reviewedAt && <> on {formatDate(entry.reviewedAt)}</>}, who {outcomeText}.
            {entry.reviewNote && <span className="block italic mt-1">&ldquo;{entry.reviewNote}&rdquo;</span>}
          </>
        ) : (
          <span className="text-amber-700">Not yet reviewed by a member of staff.</span>
        )}
      </p>

      {entry.skillVersionInstructions && !compact && (
        <details className="mt-3">
          <summary className="text-xs text-blue-600 cursor-pointer select-none">
            Show the exact instructions this agent was optimized against (v{entry.skillVersion})
          </summary>
          <pre className="mt-2 text-xs bg-gray-50 border border-gray-200 rounded p-3 whitespace-pre-wrap text-gray-700">
            {entry.skillVersionInstructions}
          </pre>
        </details>
      )}
    </div>
  )
}
