/** Action → category mapping for audit log filter chips.
 *  Kept outside 'use server' files — plain objects cannot be exported from server action modules. */
export const AUDIT_CATEGORIES: Record<string, string[]> = {
  send:     ['ILP_CREATED','ILP_ACTIVATED','ILP_REVIEWED','ILP_SHARED_WITH_PARENT','ILP_EVIDENCE_REQUESTED','SEND_STATUS_CHANGED','AI_ILP_GENERATED','K_PLAN_UPDATED'],
  homework: ['HOMEWORK_CREATED','HOMEWORK_PUBLISHED','HOMEWORK_ADAPTED','SUBMISSION_GRADED','GRADE_OVERRIDDEN','SUBMISSION_RETURNED','RESUBMISSION_REQUESTED','AI_HOMEWORK_GENERATED'],
  users:    ['USER_CREATED','USER_ROLE_CHANGED','USER_DEACTIVATED','USER_SETTINGS_CHANGED','STAFF_CREATED','STAFF_UPDATED','STAFF_DEACTIVATED','STAFF_REACTIVATED','STAFF_DELETED','STUDENT_CREATED','STUDENT_UPDATED','STUDENT_DEACTIVATED','STUDENT_REACTIVATED','STUDENT_DELETED','CLASS_CREATED','CLASS_UPDATED','CLASS_TEACHER_ASSIGNED','CLASS_TEACHER_REMOVED','STUDENT_ENROLLED','STUDENT_UNENROLLED'],
  lessons:  ['LESSON_PUBLISHED','RESOURCE_UPLOADED','LESSON_SUPPORT_REQUESTED'],
  system:   ['WONDE_SYNC_COMPLETED','ADAPTATION_APPLIED','INTEGRITY_FLAGGED','INTEGRITY_REVIEWED','MESSAGE_SENT','PLAN_NOTE_ADDED','TA_NOTE_ADDED','TA_NOTE_DELETED','AGENT_RUN_COMPLETED','AGENT_RECOMMENDATION_CONFIRMED','AGENT_RECOMMENDATION_OVERRIDDEN','AGENT_RECOMMENDATION_DISMISSED'],
}
