import { NextResponse } from 'next/server'
import { requireAuth } from '@/lib/session'
import { prisma } from '@/lib/prisma'

const ALLOWED = ['SENCO', 'SLT', 'SCHOOL_ADMIN']

function escapeCsv(val: string | number | null | undefined): string {
  const s = String(val ?? '')
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`
  }
  return s
}

function fmtDate(d: Date | null | undefined): string {
  if (!d) return '—'
  return new Date(d).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}

export const maxDuration = 60

export async function GET() {
  const user = await requireAuth()
  if (!ALLOWED.includes(user.role)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const plans = await prisma.ehcpPlan.findMany({
    where:   { schoolId: user.schoolId },
    include: {
      student:  { select: { firstName: true, lastName: true, yearGroup: true, tutorGroup: true } },
      outcomes: { select: { id: true } },
    },
    orderBy: [{ status: 'asc' }, { reviewDate: 'asc' }],
  })

  const header = [
    'Student', 'Year', 'Tutor Group',
    'Status', 'Local Authority', 'Plan Date', 'Review Date',
    'Coordinator', 'Outcomes', 'Auto Generated', 'Approved by SENCO',
  ]

  const rows = plans.map(p => [
    `${p.student.lastName}, ${p.student.firstName}`,
    p.student.yearGroup ?? '—',
    p.student.tutorGroup ?? '—',
    p.status,
    p.localAuthority,
    fmtDate(p.planDate),
    fmtDate(p.reviewDate),
    p.coordinatorName ?? '—',
    p.outcomes.length,
    p.autoGenerated ? 'Yes' : 'No',
    p.approvedBySenco ? 'Yes' : 'No',
  ])

  const csv = [
    header.map(escapeCsv).join(','),
    ...rows.map(r => r.map(escapeCsv).join(',')),
  ].join('\r\n')

  const date = new Date().toISOString().slice(0, 10)

  return new NextResponse(csv, {
    status: 200,
    headers: {
      'Content-Type':        'text/csv; charset=utf-8',
      'Content-Disposition': `attachment; filename="ehcp-status-${date}.csv"`,
    },
  })
}
