import Link from 'next/link'

const sections = [
  {
    heading: 'Lesson planning & resources',
    icon: 'edit_calendar',
    color: 'blue',
    features: [
      { name: 'Weekly teacher calendar', desc: 'Drag-and-drop lesson planning with class, subject, and year-group views.' },
      { name: 'Oak National Academy integration', desc: 'Search and add 11,000+ Oak lessons directly to any lesson plan — slides, quizzes, and videos included.' },
      { name: 'School resource library', desc: 'Upload, tag, and share lesson resources across departments. SEND accessibility scores auto-generated by AI.' },
      { name: 'AI resource generator', desc: 'Generate lesson plans, worksheets, and quizzes from a topic description using Claude.' },
      { name: 'Cover management', desc: 'Weekly cover view, absence logging, and staff availability — including timetable-based assignment.' },
      { name: 'Year-group revision programs', desc: 'Teachers build structured revision programs; students complete tasks with AI-generated content and confidence ratings.' },
    ],
  },
  {
    heading: 'Homework & marking',
    icon: 'assignment_turned_in',
    color: 'green',
    features: [
      { name: 'Six homework types', desc: 'MCQ quiz, short answer, extended writing, MIXED, UPLOAD, and adaptive SEND variants.' },
      { name: 'AI auto-marking', desc: 'Claude marks submissions against rubrics. Teachers review and override. Per-question scoring with GCSE grade 1–9 output.' },
      { name: 'SEND-adapted variants', desc: 'EHCP adaptations, SEN Support scaffolding hints, and vocabulary support generated automatically per pupil.' },
      { name: 'Resizable two-panel marking view', desc: 'Student list on the left; submission, Q&A cards, model answers, and teacher notes on the right. Fully resizable.' },
      { name: 'ILP evidence linking', desc: 'After marking, teachers are prompted to link the submission to ILP targets. AI pre-classifies each goal as PROGRESS / CONCERN / NEUTRAL.' },
      { name: 'Homework reminders', desc: 'Automated email reminders to students before due dates and notifications when homework is returned.' },
    ],
  },
  {
    heading: 'SEND & ILP management',
    icon: 'accessibility_new',
    color: 'purple',
    features: [
      { name: 'ILP builder', desc: 'Create and manage Individual Learning Plans with SMART targets, review dates, and strategy banks.' },
      { name: 'EHCP plans', desc: 'Annual review generation, outcome tracking, and provision linking — all EHCP-aligned.' },
      { name: 'K Plan management', desc: 'Kept for schools using the Local Authority K Plan framework alongside ILPs.' },
      { name: 'Early-warning flags', desc: 'Nightly cron checks submission patterns, concern frequency, and grade drops — flags at-risk students before SENCO review.' },
      { name: 'AI agent pipeline', desc: 'Three nightly agents: COACH (adaptive insights), QUALITY (Bloom\'s & SEND adaptation scoring), PLAN_SYNTHESIS (ILP/EHCP/K Plan coherence).' },
      { name: 'SENCO agent review UI', desc: 'SENCO confirms, overrides, or dismisses AI recommendations from the /senco/agent-insights dashboard.' },
      { name: 'ILP evidence timeline', desc: 'Every linked homework submission appears on the student\'s ILP page as dated evidence for reviews and APDR cycles.' },
      { name: 'SEND resource scorer', desc: 'Score any lesson plan or resource 0–100 for SEND accessibility using the built-in AI scorer.' },
    ],
  },
  {
    heading: 'Analytics & reporting',
    icon: 'bar_chart',
    color: 'teal',
    features: [
      { name: 'GCSE grade analytics', desc: 'All scores shown as GCSE 1–9 grades. Class averages, trend lines, and predicted vs actual grade comparisons.' },
      { name: 'RAG attainment views', desc: 'Per-class and per-student green/amber/red attainment status. SEND gap analysis built in.' },
      { name: 'Adaptive learning analytics', desc: 'Bloom\'s taxonomy heatmaps, per-student weak-topic detection, and preferred learning format insights.' },
      { name: 'SLT national benchmarks', desc: 'School GCSE averages compared to 2024 JCQ national averages per subject, with delta indicators.' },
      { name: 'HOY pastoral overview', desc: 'Year-group attainment, SEND flags, integrity signals, and concern history per student.' },
      { name: 'Student grade history', desc: 'Students see their own grade history per subject — sparklines, topic heatmap, and format breakdown.' },
    ],
  },
  {
    heading: 'Admin & compliance',
    icon: 'admin_panel_settings',
    color: 'amber',
    features: [
      { name: 'Wonde MIS sync', desc: 'Full sync of staff, students, classes, timetables, and contacts from any Wonde-connected MIS.' },
      { name: 'GDPR consent management', desc: 'Consent purposes, per-student consent matrix, CSV export, and data subject request log.' },
      { name: 'Filterable audit log', desc: 'Every significant action is logged — SCHOOL_ADMIN and SLT can filter by user, date, and action type.' },
      { name: 'Multi-tenant architecture', desc: 'Every query is scoped by school. No data leaks between tenants. PLATFORM_ADMIN school oversight separate from school data.' },
      { name: 'Role-based access control', desc: '12 roles with route-level enforcement. SENCO cannot mark homework; students cannot access staff analytics.' },
    ],
  },
  {
    heading: 'Student & parent experience',
    icon: 'people',
    color: 'rose',
    features: [
      { name: 'Student homework dashboard', desc: 'Filter by status (Overdue, Due soon, Graded). One-click submission with auto-save draft.' },
      { name: 'Revision planner', desc: 'Students add exams, generate a revision timetable, and work through AI-written revision tasks with confidence ratings.' },
      { name: 'Adaptive test mode', desc: 'Difficulty auto-adjusts based on student performance within a revision session.' },
      { name: 'Parent portal', desc: 'Parents view progress, manage GDPR consent, and message staff — all in a role-specific interface.' },
      { name: 'Messaging', desc: 'Threaded messaging between all staff, students, and parents. Unread badge with 60s poll.' },
    ],
  },
]

const colorMap: Record<string, { bg: string; border: string; icon: string; tag: string }> = {
  blue:   { bg: 'bg-blue-50',   border: 'border-blue-100',   icon: 'text-blue-700',   tag: 'bg-blue-100 text-blue-700' },
  green:  { bg: 'bg-green-50',  border: 'border-green-100',  icon: 'text-green-700',  tag: 'bg-green-100 text-green-700' },
  purple: { bg: 'bg-purple-50', border: 'border-purple-100', icon: 'text-purple-700', tag: 'bg-purple-100 text-purple-700' },
  teal:   { bg: 'bg-teal-50',   border: 'border-teal-100',   icon: 'text-teal-700',   tag: 'bg-teal-100 text-teal-700' },
  amber:  { bg: 'bg-amber-50',  border: 'border-amber-100',  icon: 'text-amber-700',  tag: 'bg-amber-100 text-amber-700' },
  rose:   { bg: 'bg-rose-50',   border: 'border-rose-100',   icon: 'text-rose-700',   tag: 'bg-rose-100 text-rose-700' },
}

export default function FeaturesPage() {
  return (
    <main className="max-w-6xl mx-auto px-6 py-16">
      <div className="text-center mb-16">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">Platform features</h1>
        <p className="text-gray-500 text-lg max-w-2xl mx-auto">
          A complete overview of everything Omnis does — from first lesson to annual review.
        </p>
      </div>

      <div className="space-y-16">
        {sections.map(({ heading, icon, color, features }) => {
          const c = colorMap[color]
          return (
            <section key={heading}>
              <div className="flex items-center gap-3 mb-6">
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${c.bg} ${c.border} border`}>
                  <span className={`material-icons ${c.icon}`}>{icon}</span>
                </div>
                <h2 className="text-2xl font-bold text-gray-900">{heading}</h2>
              </div>
              <div className="grid md:grid-cols-2 gap-4">
                {features.map(({ name, desc }) => (
                  <div key={name} className={`rounded-xl border p-5 ${c.bg} ${c.border}`}>
                    <div className="flex items-start gap-3">
                      <span className={`material-icons text-base mt-0.5 shrink-0 ${c.icon}`}>check_circle</span>
                      <div>
                        <p className="font-semibold text-gray-900 text-sm mb-1">{name}</p>
                        <p className="text-gray-600 text-sm leading-relaxed">{desc}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          )
        })}
      </div>

      {/* CTA */}
      <div className="mt-20 bg-blue-700 rounded-2xl p-10 text-center text-white">
        <h2 className="text-2xl font-bold mb-3">Interested in bringing Omnis to your school?</h2>
        <p className="text-blue-100 mb-6">We&apos;re accepting beta schools now. No commitment — just a conversation.</p>
        <Link href="/marketing/beta" className="bg-white text-blue-800 font-semibold px-8 py-3 rounded-xl hover:bg-blue-50 transition-colors inline-block">
          Apply for beta access
        </Link>
      </div>
    </main>
  )
}
